catchorg/Catch2

include/internal/catch_commandline.hpp
include/internal/catch_config.hpp
include/internal/catch_console_colour_impl.hpp
include/internal/catch_interfaces_config.h
projects/SelfTest/TestMain.cpp

Adding a --force-colour option to force colour output on POSIX systems,
provided a debugger is not attached.
This allows for Catch to output colours even if STDOUT is not a tty,
which can be the case when the test executable is being spawned by a
parent process (e.g. CMake's ctest).

Add --force-colour option to force colour output.

---

include/internal/catch_console_colour_impl.hpp

In powershell the text background appears white
In the current implementation the original background is overwritten when coloring text. This commit splits the foreground and background color attributes. I have tested it with both power-shell and command line.

Fix for white background in windows powershell when using colour output.

---

include/internal/catch_matchers.hpp

A generic Not() matcher to get nice readable test code a la
```
CHECK_THAT(address1, Not(Equals(address2)));
```
[Used and tested in Botan.](https://github.com/randombit/botan/blob/master/src/tests/catchy/test_x509.cpp)

Add matcher: Not()

---

include/internal/catch_capture.hpp

Hi !
I found an issue using ccache.
To reproduce it, just add ccache & gcc options in your CMakeList:
```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -rdynamic -Wall -Werror")
set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
```
Then try to build a simple test:
```c++
SCENARIO("test")
{
GIVEN("givenTest")
{
int i = 1;
WHEN("whenTest")
{
REQUIRE(i == 1);
}
}
}
```
Y'oull get the following output:
```
error: suggest parentheses around comparison in operand of ‘==’ [-Werror=parentheses]
REQUIRE(i == 1);
```
Fix it by adding parenthesis around `expr` in `INTERNAL_CATCH_TEST`

Fix parentheses warning on expression evaluation when using ccache

---

include/internal/catch_compiler_capabilities.h

This fixes issue #600.  The [documentation of GCC](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html) makes it look like "GCC" needs to be capitalized in this pragma.  If you don't capitalize the pragma, GCC warns that it doesn't recognize the pragma.

Capitalize "GCC" in pragma

---

include/reporters/catch_reporter_bases.hpp

Added missing CATCH_OVERRIDE to CumulativeReporterBase::assertionEnded(). This fixes a warning when building in Xcode 7.2+ with default warning settings.

Fixed warning for missing CATCH_OVERRIDE

---

.travis.yml

Resolves https://github.com/philsquared/Catch/commit/e904aa7f6e2e450f9515bce96a0c4b5669ed5d93#commitcomment-17389109.
Context: when LLVM released LLVM 3.8 they switched the repository `llvm-toolchain-precise` to track LLVM 3.9 and created a `llvm-toolchain-precise-3.8` for LLVM 3.8.

Pins LLVM 3.8 (stable) instead of tracking the nightly repository

---

include/internal/catch_test_case_registry_impl.hpp

Instead of `exit(1)`, it now throws `std::runtime_error` with the details
of the failure. This exception is handled in `run()` at a higher level where
the log is printed to cerr and the test gracefully exits.

[#608] Don't use exit() on duplicate test descriptions

---

include/reporters/catch_reporter_xml.hpp

SCENARIO does not add leading spaces to the test name (only BDD-style section
names are modified), so the trimming is not necessary. But if the name is
trimmed, it makes it harder to correlate the output of XML reporter with tests
that have leading spaces in their name: e.g. these tests will have the same name
attribute:
```
TEST_CASE("Test") {}
TEST_CASE(" Test") {}
```

Do not trim test case names in the XML reporter.

---

include/internal/catch_xmlwriter.hpp
projects/SelfTest/MiscTests.cpp

This commit fixes the following scenario:
* You have a test that compares strings with embedded control
characters.
* The test fails.
* You are using JUnit tests within TeamCity.
Before this commit, the JUnit report watcher fails on parsing the XML
for two reasons: the control characters are missing a semicolon at the
end, and the XML document doesn't specify that it is XML 1.1.
XML 1.0 --- what we get if we don't specify an XML version --- doesn't support embedding control characters --- see
http://stackoverflow.com/questions/404107/why-are-control-characters-illegal-in-xml
for all of the gory details.
This is based on PR #588 by @mrpi

Fixes for XML encoding.

---

include/internal/catch_test_spec.hpp

This (and all bugs akin) could (and honestly should) be fixed by enforcing a `.clang-format` at repository root
Closes #679

Fix misindent in internal/catch_test_spec.hpp:70

---

include/internal/catch_common.hpp
include/internal/catch_test_case_registry_impl.hpp

We (the Visual Studio STL team) are trying to remove suppression of C4244 in `<algorithm>`, which exposed stealth narrowing conversions in Catch.

Fix fix implicit narrowing warnings in Catch

---

include/internal/catch_stream.h

This fixes issue #749.
However, I think it would be better to `#include <memory>` when defining `CATCH_AUTO_PTR` macro, instead of forcing catch headers to include `<memory>` when using the macro.

Fixes build error caused by missing include.

---

docs/tutorial.md

It's = it is
its = possessive it
In the sentence "In fact it is usually a good idea to put the block with the `#define` [in it's own source file](slow-compiles.md).", the correct usage is "its", not "it's".

Fix grammar error in tutorial.md

---

include/catch.hpp

`INTERNAL_CATCH_THROWS` now takes a matcher as the third argument, but `CATCH_CHECK_THROWS` was not updated to accommodate that. This PR should resolve that.

add missing argument to CATCH_CHECK_THROWS (closes #602)

---

include/internal/catch_result_builder.hpp

When if( m_exprComponents.op == "" ) is true, there is no need to concatenate with m_exprComponents.op.

Remove concatenation of empty string in ResultBuilder::reconstructExpression()

---

include/internal/catch_approx.hpp
projects/SelfTest/ApproxTests.cpp

Add support for <= and >= for Approx

---

include/internal/catch_xmlwriter.hpp

At the moment Catch encodes (assuming signed char) characters from extended ASCII encodings in the XML reporter. This was probably not intended (since only control characters should be escaped), and is also a problem for XML parsers which do not understand XML v1.1 yet (like .NET's XmlReader).

Do not encode extended ASCII characters in XML reporter

---

include/internal/catch_debugger.h
include/internal/catch_debugger.hpp
include/internal/catch_platform.h

This makes `-b` command line option to work under Linux.
Only tested under amd64, but should work on any architectures, in theory.

Implement support for breaking into debugger under Linux

---

include/catch.hpp

Hi!
I was just reviewing the code and found this small typo. Great project though! 
Cheers!
JP

Fix missing CATCH_ for CHECK_THAT in prefixed macro version

---

include/internal/catch_capture.hpp
include/internal/catch_common.h

There were numerous different ideas and scattered code snippets in #574. This PR gathers the pieces to implement the `sizeof` approach.

use sizeof(expr) for unevaluated syntax check

---

include/internal/catch_debugger.h

The integrated assembler segment was missing an underscore:
`"_asm__"`. This regression was accidentally introduced in: https://github.com/philsquared/Catch/commit/25d017763b73e09d3e9adf7f4db9ce71992f0471#diff-96e75ad10f6edace03f2cb7d3607de00L34
Also we remove the "DEBUG" macro check, so we are consistent
with the linux and windows variant.
Now breaking into gdb on failure should work via:
`gdb --args test_executable --break`
I tested this to work on Mac OS 10.11.6 using GNU gdb (GDB) 7.12.

Enable breaking into debugger on Mac

---

CMakeLists.txt

Even though CATCH is a header only library, it makes sense to allow it to INSTALL the includes in a standard manner. This is especially useful when adding dependencies using the CMake ExternalProject_Add command as an example.

Added INSTALL commands

---

docs/own-main.md
include/internal/catch_default_main.hpp

According to POSIX, only lower 8-bits of a program exit code are available through `wait()` and `waitpid()` calls. Although there is a newer `waitid()` interface, I think most of the programs still use the old one. As a result, multiples of 256 wrap to 0 for these programs.
This pull request sets cap to 255 for the default main exit code for better compatiblity. Also the documentation for own-main() is updated.
Tested on macOS Sierra with zsh and Fedora 25 with bash.
```c++
#define CATCH_CONFIG_MAIN
#include <catch.hpp>
TEST_CASE("256 failures")
{
for (int i = 0; i < 256; i++) {
CHECK(false);
}
}
```
```
$ ./before; echo "exit_code: $?"
...
test cases:   1 |   1 failed
assertions: 256 | 256 failed
exit_code: 0
```
```
$ ./after; echo "exit_code: $?"
...
test cases:   1 |   1 failed …
```

Cap main exit code to 255

---

include/reporters/catch_reporter_tap.hpp

This PR fixes an issue within the TAP reporter that causes it not to count success tests in absence of the `-s` switch, resulting in it always printing `1..0`.

TAP Reporter: count success tests even if not printed

---

include/catch_session.hpp
include/internal/catch_version.h
include/internal/catch_version.hpp
include/reporters/catch_reporter_console.hpp
scripts/releaseCommon.py

This PR changes `libraryVersion` to be an inline function, rather than an extern struct. This resolves an issue where Catch could crash when a process exits if multiple libraries acting as a Catch 'main' are loaded, as this can lead to double-destruction of the Version struct on exit.
Let me know if this looks appropriate -- I also modified the release script parser to handle the new layout of how the version is declared.
Note that this would potentially break any users who were using the `libraryVersion` struct in their own code.

use inline 'libraryVersion()' function (closes #858)

---

include/internal/catch_message.hpp
include/reporters/catch_reporter_console.hpp
projects/SelfTest/ExceptionTests.cpp

print messages when unexpected exceptions are thrown

---

docs/configuration.md
include/internal/catch_tostring.h
projects/SelfTest/CompilationTests.cpp

It adds opt-in define `CATCH_CONFIG_CPP_11_STREAM_INSERTABLE_CHECK` for enabling C++11 stream insertable check which should be better in some cases as suggested by @philsquared in #872.
All current tests seem to pass fine with it on my system.
Should I also add it to documentation somewhere?
PR should resolve #872 and #757 for those who opt-in.

Add opt-in c++11 stream insertable check.

---

contrib/ParseAndAddCatchTests.cmake

#719
this is a cmake script which can be used for automatic CTest generating by parsing c++ sources for CATCH tests.
When you'd like to add CTest test you are usually doing this:
enable_testing()
add_test(...)
add_test(...)
Instead of the adding each test manually, I suggest to try using of this script which parses and adds found CATCH tests into cmake project
enable_testing()
include(ParseAndAddCatchTests)
ParseAndAddCatchTests(${PROJECT_NAME})
Notice 1: this script is a simplified version of Fraser999's scripts
Notice 2: this script doesn't replace and doesn't contain cmake commands for the adding CATCH lib into the project

cmake script to generate ctest definitions from catch tests

---

contrib/ParseAndAddCatchTests.cmake

If source files are defined using relative paths, CMake will compile the tests, but this script will (sometimes) fail to find and parse the tests from the source files.  I have added an explicit warning when ParseAndAddCatchTests fails to find a source file.
ParseAndAddCatchTests will fail without warning when it cannot find source files to parse. There are instances where CMake will find sources to compile the executable, but ParseAndAddCatchTests fails to find those same source files when using relative paths. This can lead to confusion for the end user when CMake and make compile code without errors, yet running `make test` or `ctest` reports that there are no tests to run. An explicit warning allows users to resolve potential path problems.
I decided to fix this problem myself instead …

Added warning if source file cannot be found

---

CMakeLists.txt
appveyor.yml
include/catch_session.hpp
include/internal/catch_default_main.hpp

Added alternate main definition, available on Win32 platforms, when UNICODE
support is enabled. argv command line is a wchar_t, so Catch run interface should
be adapted in order to manage it.

Added Win32 UNICODE wmain support

---

docs/event-listeners.md

Hey,
I added the Catch namespace in the example, as it did not compile as is.

Typo: Added namespace in method testCaseEnded

---

include/reporters/catch_reporter_teamcity.hpp

I've modified the teamcity reporter to time individual test cases. TeamCity can time tests without reporting duration explicitly however the timing can be subject to network latency.
See the teamcity [documentation](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Supportedtestservicemessages) for the duration attribute on the testFinished service message.

teamcity reporter should time durations explicitly

---

contrib/ParseAndAddCatchTests.cmake

Made some improvements to ParseAndAddCatchTests.cmake script:
- use absolute path to test files - accroding to CMake docs EXISTS behavior is well-defined only for full paths
- added option to print debug messages
- added target name to test name and labels - to differentiate tests with similar names from different targets and to be able to run all tests coming from one target.

CTest integration script enhancements

---

include/internal/catch_expression_lhs.hpp

Types which are truthy, but have more information than the truthiness in their string conversion were showing up as 'true' or 'false' instead of showing the underlying type's string value.

ExpressionLhs reconstruction based on value, not truthiness

---

include/internal/catch_tostring.h
include/internal/catch_tostring.hpp

Fix Catch::toString() linker error when main() is compiled as C++

---

include/internal/catch_assertionresult.h
include/internal/catch_assertionresult.hpp
include/internal/catch_result_builder.hpp
include/internal/catch_run_context.hpp

By using char const * instead of std::string we avoid significant
copying per assertion.  In a simple loop with 10000000 CHECKS on
my system, this reduces the run time from 9.8s to 6s.

Performance improvement in AssertionInfo.

---

include/internal/catch_result_builder.h
include/internal/catch_result_builder.hpp

This is not thread safe, but I think that was already true of Catch.
The construction/destruction of the std::ostringstream is where the
vast majority of time is spent per assertion.  A simple test of
100000000 CHECK()s is reduced from around 60s to 7.4s

Cache std::ostringstream between assertions.

---

include/internal/catch_commandline.hpp
include/internal/catch_config.hpp
include/internal/catch_list.hpp

this will add line info to test lists, and test descriptions to the long
form of the test list
Related to issue #930

add --extra-info flag

---

include/internal/catch_capture.hpp
include/internal/catch_interfaces_capture.h
include/internal/catch_result_builder.h
include/internal/catch_result_builder.hpp
include/internal/catch_run_context.hpp

I need some help with this one.  I've eliminated the vast majority of work in the cases that the results won't be reported (in general success).  It passes all but one tiny portion of the tests, which I'm hoping you'll know what I've missed.  This will get us from 7.6s->2.7s if I can figure out the last little piece.
After this half the work remaining is the m_stream.oss.str("") in the constructor, and the other half may be the m_stream.oss.str() in build().

Eliminate some work when results won't be reported.

---

include/reporters/catch_reporter_bases.hpp
single_include/catch.hpp

As reported in #961 dynamically generated sections are not correctly reported when using JUnit reporter. The cause of this is that only the source code line is taken into account when comparing sections in `CumulativeReporterBase` when it should also consider the section's name.
Closes #961

Fix for JUnit reporter when using dynamically generated sections

---

include/internal/catch_commandline.hpp

The "use-colour" option was accidentally duplicated as part of commit
feaf355 (Implemented libidentify support).

Remove duplicate CLI option

---

include/internal/catch_compiler_capabilities.h

1. Use it to conditionally define `CATCH_INTERNAL_CONFIG_COUNTER`, not
`CATCH_CONFIG_COUNTER`, as `__JETBRAINS_IDE__` is similar to
compiler-provided macros, not to user-provided ones.
2. Since `__COUNTER__` will work starting with CLion 2017.3, use it
when possible (and hopefully remove this check altogether
at some point).
CLion will support `__COUNTER__` macro properly soon (https://youtrack.jetbrains.com/issue/CPP-820)

Update handling of __JETBRAINS_IDE__ macro

---

scripts/markdown_toclify.py
scripts/updateDocumentToC.py

As per [this comment](https://github.com/philsquared/Catch/issues/970#issuecomment-325700434) of issue #970. @horenmar, squash at your liking.
Adds `scripts/updateDocumentToC.py`.

[Scripts] Add script to add table of contents to markdown files

---

contrib/ParseAndAddCatchTests.cmake

Adds option to ParseAndAddCatchTests.cmake which causes CMake to rerun when test files change so that new tests will be discovered.
Resolves https://github.com/philsquared/Catch/issues/1035

added PARSE_CATCH_TESTS_ADD_TO_CONFIGURE_DEPENDS option

---

include/internal/catch_test_case_registry_impl.hpp

`result_type` must be unsigned:
http://en.cppreference.com/w/cpp/concept/UniformRandomBitGenerator
Using a signed type causes an infinite loop working with MS Visual Studio 2017, targetting: v140, WindowsTargetPlatformVersion 10.0.15063.0, Debug, x64
Simply using uint32_t seems sufficient, since the value of `max()` is small enough.

`RandomNumberGenerator::result_type` should be unsigned

---

CMakeLists.txt

to prevent inheritance of include directories that possibly lead to a clash.
A clash occurs when a folder is included, e.g. examples, that wants to use the single-include directory instead of the normal include directory as used by the SelfTest in the next higher level.
CMake: [include_directories()](https://cmake.org/cmake/help/v3.0/command/include_directories.html)
CMake: [target_include_directories()](https://cmake.org/cmake/help/v3.0/command/target_include_directories.html)
Aside: I am a little surprised that the CMake description for SelfTest is in the toplevel `CMakeFiles.txt` and not in e.g. `projects/SelfTest/CMakeFiles.txt`.

Replace include_directories() with target_include_directories()

---

include/internal/catch_platform.h

Platform detection fails for iOS resulting in compile error.
The `TARGET_OS_MAC` is a super category of `TARGET_OS_OSX` and `TARGET_OS_IPHONE` thus `CATCH_PLATFORM_IPHONE` is never selected. 
From apple docs:
```
TARGET_OS_* 
These conditionals specify in which Operating System the generated code will
run.  Indention is used to show which conditionals are evolutionary subclasses.  
The MAC/WIN32/UNIX conditionals are mutually exclusive.
The IOS/TV/WATCH conditionals are mutually exclusive.
TARGET_OS_WIN32           - Generated code will run under 32-bit Windows
TARGET_OS_UNIX            - Generated code will run under some Unix (not OSX) 
TARGET_OS_MAC             - Generated code will run under Mac OS X variant
TARGET_OS_OSX          - Generated code will run under OS X devices …
```

Fix platform detection for iOS

---

.travis.yml
CMakeLists.txt
appveyor.yml
docs/event-listeners.md
docs/list-of-examples.md
docs/tutorial.md
examples/000-CatchMain.cpp
examples/010-TestCase.cpp
examples/020-TestCase-1.cpp
examples/020-TestCase-2.cpp
examples/030-Asn-Require-Check.cpp
examples/100-Fix-Section.cpp
examples/110-Fix-ClassFixture.cpp
examples/120-Bdd-ScenarioGivenWhenThen.cpp
examples/210-Evt-EventListeners.cpp
examples/CMakeLists.txt

PR linked to issue #1037.
I've integrated building of the examples into CMake.
**`USE_EXAMPLES`**&emsp;The examples are built if `USE_EXAMPLES` is `true`. This name follows the existing pattern, but may not properly reflect the choice. `NO_EXAMPLES` is the wrong way round. Plain `EXAMPLES` is weird.
Do you have suggestions?
**Travis, AppVeyor**&emsp; I've not touched CI yet. Do you have suggestions here; I wouldn't mind to leave this to experts.
Other remarks?

Add example code linked to from documentation, part 1

---

include/reporters/catch_reporter_console.cpp

Fix AssertionPrinter name conflict in console and compact reporters

---

docs/opensource-users.md

Add [Inja](https://github.com/pantor/inja) to the list of open source libraries using Catch2.

Add inja to open source users

---

include/internal/catch_assertionhandler.cpp

Begin to address #1086
Brings test from 2m51.072s to 1m15.661s

Performance improvement

---

include/internal/catch_context.cpp
include/internal/catch_context.h
include/internal/catch_stringref.cpp
include/internal/catch_stringref.h

inlined StringRef::operator= and reduced data copy in half.
Brings test from 0m44.942s to 0m37.913.
inlined getCurrentContext and getMutableContext
Brings test from 0m37.913 to 0m25.584s
Catch2 is now faster than Catch 1.x!!

performance improvements

---

contrib/Catch.cmake
contrib/CatchAddTests.cmake

Copied from [Dynamic Catch test discovery in CMake](https://gist.github.com/garethsb/a01ed0dbd4977d439c16200640549935), which was inspired by [Dynamic Google Test Discovery in CMake 3.10](https://blog.kitware.com/dynamic-google-test-discovery-in-cmake-3-10/).
Original source code:
- Adapted from [GoogleTest ``gtest_discover_tests``](https://gitlab.kitware.com/cmake/cmake/merge_requests/1056).
- BSD 3-clause "New" or "Revised" License.
- Copyright 2000-2017 Kitware, Inc. and Contributors. All rights reserved.
See issue #1099.

Catch ``catch_discover_tests`` for robust dynamic discovery of Catch tests in CMake

---

CMakeLists.txt
appveyor.yml
catch.pc.in

1. Do not build tests with `-Werror` by default
`-Werror` is good for CI testing but causes massive integrations issues, as compilers add warnings that developers cannot foresee. See also:
- https://bugs.gentoo.org/644354
- https://blog.flameeyes.eu/2009/02/future-proof-your-code-dont-use-werror/
2. Install documentation
3. Use CTest to control test suite via `BUILD_TESTING`. The `CTest` module, like `GNUInstallDirs`, provides an idiomatic way to enable and disable the testsuite.
4. Use `GNUInstallDirs` module
`GNUInstallDirs` is a standardised way to change paths, which makes systems integration easier and allows for a more consistent user experience.

CMake fixes

---

.travis.yml
CMakeLists.txt
catch.pc.in
examples/CMakeLists.txt
misc/appveyorBuildConfigurationScript.bat
scripts/releaseCommon.py

1. Use `VERSION` specifier in `project()`. This is the modern idiomatic CMake way of specifying the version, for instance see https://rix0r.nl/blog/2015/08/13/cmake-guide/. All regexes for the build scripts have been updated.
2. Namespace all Catch options as suggested by @martinmoene

More CMake fixes

---

CMakeLists.txt
include/internal/catch_compiler_capabilities.h
include/internal/catch_message.cpp
include/internal/catch_section.cpp
include/internal/catch_uncaught_exceptions.cpp
include/internal/catch_uncaught_exceptions.h

[N4152](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4152.pdf) deprecates `std::uncaught_exception`.
A minimal patch satisfying #1162 , although I am unclear whether or how to support older compilers here. (cf. #927 )

N4152 C++17

---

include/internal/catch_decomposer.h
include/internal/catch_tostring.h
include/reporters/catch_reporter_junit.cpp
projects/SelfTest/TestMain.cpp

I have a [meson](http://mesonbuild.com/) build that will build and run the Catch tests when Catch is used as a subproject. Those tests fail to build with the `-Wpedantic` flag because of the extra semicolons removed by this PR. This is very minor, but I figured I'd go ahead and submit in case you want the changes.
(Also, I don't know if you want to support a meson build in addition to CMake, but if that sounds appealing let me know and I will submit a PR.)
Thanks!

Remove unnecessary semicolons

---

CMakeLists.txt

Create a namespaced catch::catch target that is 'linkable' through
`target_link_libraries()` and export it so it is findable through
`find_package()`.
This makes catch a lot easier to use in CMake-based projects. Whether it
is found using `find_package` or included in the client project as a
subdirectory, the client can include the catch headers per-target with
`target_include_directories(target PRIVATE catch::catch).
Also exported is a catch-config-version.cmake file that handles
versions if specified through `find_package(catch 2.1.1 REQUIRED)`.
It will find versions with the exact same major number and with a minor
number >= specified minor number.
LIMITATIONS: As catch.hpp is stored inside the single_include directory,
but installed to include/catch, the `#include` directive changes …

Export catch as cmake package and as a 'linkable' target

---

CMakeLists.txt
include/internal/catch_commandline.cpp
include/internal/catch_config.cpp
include/internal/catch_config.hpp
include/internal/catch_interfaces_config.h
include/internal/catch_session.cpp
include/internal/catch_totals.h

added -w NoTests switch.
added error indication to Totals so that return code won't be 0.
resolves https://github.com/catchorg/Catch2/issues/1158

add option to warn when no tests ran

---

include/internal/catch_fatal_condition.cpp

The warning occurred when !CATCH_CONFIG_WINDOWS_SEH && !CATCH_CONFIG_POSIX_SIGNALS which is the case in my setup.

Fix 'defined but not used' warning

---

docs/configuration.md
include/internal/catch_compiler_capabilities.h
include/internal/catch_console_colour.cpp
include/internal/catch_default_main.hpp
include/internal/catch_session.cpp
include/internal/catch_session.h
include/internal/catch_tostring.cpp
include/internal/catch_tostring.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Matchers.tests.cpp
projects/SelfTest/UsageTests/Misc.tests.cpp

The support is turned on by default but the user might need to be able
to turn it off which is now possible by defining CATCH_CONFIG_NO_WCHAR.
The motivation behind this is to add the support (on which I'm working on) for a new compiler - DJGPP cross compiler. This compiler is gcc based and is targeting DOS. It does not support wchar_t nor std::wstring probably because there would not be much use of them in DOS.
As for the testing, one Travis' job could, in theory, be dedicated to test with CATCH_CONFIG_NO_WCHAR defined but I don't know whether it's worth it now. It is not a breaking change and the final DJGPP support should of course include tests (one Travis job to build the tests and run them in DOSBox).
This is the first necessary step to support DJGPP cross compiler. If you are not …

Introduce conditional wchar_t (and std::wstring) support

---

include/internal/catch_matchers_floating.cpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Matchers.tests.cpp

I encountered a condition in `WithinAbs()` that should not fail from my understanding of that feature.
Looking into the code, I believe I found the issue.
Added a few selftests that would have pointed out this problem before the fix.
Obviously `approvalTests.py` fails and reports theses new tests but guess I'm not supposed to approve these differences.

fix typo in WithinAbs::match() and add selftests that would have failed previously

---

include/internal/catch_suppress_warnings.h

Fixes an issue where catch silences some GCC compiler warnings in the unit test.
`#pragma GCC diagnostic push` should come before any warnings are ignored.
Moving the push to the before any other GCC pragma means any warnings ignored in catch will be restored at end of the header by `#pragma GCC diagnostic pop`
Clang also does not have the push pragma first. Should that also be updated?
Is there a good reason that I have missed for allowing some warning pragma to leak?
Closes #1090.

Stop GCC warning suppression leaking out of catch

---

catch.pc.in

In CMake module both include and include/catch are added to includes
lookup path. Examples are built with #include "catch.hpp" not #include "catch/catch.hpp". 
This should be the same with pkg-config.
Fixing pc file would ease Catch2 use from build systems like [Meson](http://mesonbuild.com/index.html).

Small fix to generate pc with all include path

---

include/internal/catch_tostring.h

Changes to allow stringification of CLR objects. This enables REQUIRES(a == b) and such print proper strings in reports when used with CLR objects.
I have been using Catch2 in C++/CLI and this helps make it nicer.

CLR Object Stringify

---

docs/assertions.md
include/internal/catch_test_registry.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/console.swa4.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Compilation.tests.cpp

Currently, you cannot use template specializations with commas in them as fixtures. This because you need to parenthesize them in order for the macro to treat it as a single argument, and that single argument is used as a base class type specifier... and you can't have parentheses there.
In other words, this doesn't work today:
template <typename, typename>
struct Fixture { };
TEST_CASE_METHOD((Fixture<int, int>), "a", "[b]") {
CHECK(1 == 1);
}
With less than helpful compile errors like:
```
foo.cxx:7:18: error: expected class-name before ‘(’ token
TEST_CASE_METHOD((Fixture<int, int>), "a", "[b]") {
^
foo.cxx:7:18: error: expected ‘{’ before ‘(’ token
foo.cxx:7:36: error: invalid declarator before ‘)’ token
TEST_CASE_METHOD((Fixture<int, int>), "a", "[b]") {
^
foo.cxx:7:1: error: …
```

Support for parenthesizing types with commas.

---

include/internal/catch_test_case_tracker.cpp
include/reporters/catch_reporter_bases.cpp
include/reporters/catch_reporter_bases.hpp
include/reporters/catch_reporter_junit.cpp

Now includes the c++ headers `cassert`, `csignal` and `cstdio` instead of `assert.h`, `signal.h` and `stdio.h`.
I've had problems in another multi-library project when moving to newer versions of clang when _not_ using c++ headers, although these aren't the usual culprits.
A rationale and basis for discussion is here: https://stackoverflow.com/questions/43011737/is-it-better-to-include-cassert-or-assert-h?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Changed to c++ style includes

---

include/internal/catch_test_case_info.cpp

std::isalnum expects an int in the range of unsigned char or -1 (EOF),
otherwise it exhibits undefined behavior. Casting from char to unsigned
char avoids this.
MSVC warns about this when compiling with /analyze.

Cast to unsigned char when using std::isalnum

---

docs/command-line.md

The documentation for `--use-colour` option was missing.
I added it based on the `-?` output a Catch test program gave me and the comments on #950

Add documentation for `--use-colour`

---

.travis.yml

While adding updating Catch2 for GCC 8 (see #1276), I noticed that Clang 6 is missing.
This patch will add Clang 6 to Travis.
It is separate to #1276, since #1276 also targets a warning surfaced in GCC 8.

Updated Travis for LLVM 6.0

---

.travis.yml
projects/SelfTest/UsageTests/Misc.tests.cpp

While trying to install Catch2 on a Docker system with GCC 8, I encountered this warning:
```
[32/100] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Misc.tests.cpp.o
FAILED: CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Misc.tests.cpp.o
/usr/local/bin/c++   -I/usr/src/catch/Catch2/include -O3 -DNDEBUG   -Wall -Wextra -Wunreachable-code -Wpedantic -Werror -std=c++11 -MD -MT CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Misc.tests.cpp.o -MF CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Misc.tests.cpp.o.d -o CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Misc.tests.cpp.o -c /usr/src/catch/Catch2/projects/SelfTest/UsageTests/Misc.tests.cpp
/usr/src/catch/Catch2/projects/SelfTest/UsageTests/Misc.tests.cpp: In function 'void …
```

Fixed Catch2 for GCC 8

---

contrib/gdbinit
contrib/lldbinit

The commands provided have to be executed in the current gdb/lldb session or copied
into the users ~/.gdbinit ~/.lldbinit files to permanently skip debugging Catch code.
Fixes #904

Add gdbinit and lldbinit files to skip stepping into Catch code during debugging

---

contrib/CatchAddTests.cmake

I cannot see a reason why spaces should not be allowed for CTest test names.
this fixes #1265

Do not strip spaces from cmake discovered test names

---

scripts/approvalTests.py

This method to enable colours only works on windows 10.

Enable console colour in the approval tests on windows.

---

include/internal/catch_fatal_condition.cpp

The formerly allocated stack size for POSIX signal handling was implementation defined and in many cases insufficient, leading to stack overflows in the signal handler. The new size, which was determined through experimenting, is the larger of 32kb and `MINSIGSTKSZ`.
Fixes #1225

Adjust stack size for POSIX signal handling to prevent stack overflow

---

include/internal/catch_tostring.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/ToStringWhich.tests.cpp

What: use function syntax to call operator<< in StringMaker...
Why: ...so that it is not ambiguous with user-defined templated operator<< under clang.
Currently, the code below is ambiguous between the user defined operator<< and operator<<(StringMaker&, T) because both are templates and need one substitution.
```
struct myType {/* ... */};
template <class stream>
stream& operator<<(stream& out, const myType& myT) {
out << myT.string_value();
return out;
}
```
Closes  #1285

Clang templated stream op

---

contrib/ParseAndAddCatchTests.cmake

Fix a bug where tags from one test would spill into the next test if this next text did not have any tags associated.
This simply unsets the "Tags" variable when the test does not have tags.

Properly unset tags variable.

---

include/internal/catch_matchers.h

Comping with clang and ```-Wnon-virtual-dtor``` fails as follows:
```
include/internal/catch_matchers.h:38:16: error:
'Catch::Matchers::Impl::MatcherMethod<std::__1::basic_string<char> >'
has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor
```
This CL wraps the offending code in a pragma ignore.

catch_matchers: Fix compilation error with -Wnon-virtual-dtor

---

CMakeLists.txt
projects/CMakeLists.txt

* Calling `python` does not allow overriding
downstream when running tests.

Allow overriding of Python interpreter

---

docs/configuration.md
docs/own-main.md
docs/test-cases-and-sections.md
docs/tostring.md

Replace TABs with four (4) spaces in code docs.

Docs: TABs to Spaces

---

scripts/approvalTests.py

Fix TABs and none-PEP8 spaces in approval test.
Does not yet fix overlong lines for full `flake8` compliance.

Tests: TABs to Spaces

---

docs/configuration.md
include/internal/catch_compiler_capabilities.h
include/internal/catch_tostring.cpp
include/internal/catch_tostring.h
projects/SelfTest/UsageTests/ToStringGeneral.tests.cpp

Adds StringMaker specializations for std::string_view and std::wstring_view,
so that string_views gets stringified correctly.
#1375

Add StringMaker for std::string_view

---

.travis.yml
docs/configuration.md
include/internal/catch_compiler_capabilities.h
include/internal/catch_tostring.h
projects/CMakeLists.txt
projects/SelfTest/UsageTests/ToStringVariant.tests.cpp

Adds StringMaker specializations for `std::variant` and `std::monostate`, which can be enabled with `CATCH_CONFIG_ENABLE_VARIANT_STRINGMAKER` or `CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS`.
Also includes configuration macros for detecting C++17 and <variant> header presence, so it doesn't break the build for anyone on C++ < 17 who's using `CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS`.
Tests are modelled after the tuple tests.

Add StringMaker for std::variant, std::monostate

---

include/internal/catch_run_context.cpp

Changes the `aborting()` comparison to also handle when `m_totals.assertions.failed` is greater than `m_config->abortAfter()`.
It is possible for this to occur under incorrect (but valid) use of assertions such as `REQUIRED`.
Fixes issue https://github.com/catchorg/Catch2/issues/1391

Abort when assertions failed is greater than or equal to config value

---

include/internal/catch_compiler_capabilities.h

What: Made a change to restrict to_string for compilers on specific cygwin systems.
Why: std::to_string doesn't exist on some cygwin compiler systems. 
Fixes #1396 
Used the same preprocessor test as found in the libstd for basic_string:
https://gcc.gnu.org/onlinedocs/gcc-4.8.2/libstdc++/api/a01053_source.html

Fix Cygwin compiler error

---

include/internal/catch_tostring.cpp

Some platforms set the signedness of char to unsigned (eg. ARM).
Convert from char should not assume the signedness of char.
Fix build issue with -Werror,-Wtautological-unsigned-zero-compare flags.
Signed-off-by: Miguel Gaio <mgaio35@gmail.com>
This fix build issue on ARM target with -Werror,-Wtautological-unsigned-zero-compare flags.
Following compiler logs is observed
catch2/include/internal/catch_tostring.cpp:217:21: error: comparison of 0 <= unsigned expression is always true [-Werror,-Wtautological-unsigned-zero-compare]
} else if ('\0' <= value && value < ' ') {
N/A

Fix convert from char on ARM build

---

include/internal/catch_common.h
include/internal/catch_tostring.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/console.swa4.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Compilation.tests.cpp

Originally I reported a bug, [1403](https://github.com/catchorg/Catch2/issues/1403) about how user code provides an insertion overload (an overload for `operator<<`) for an `std` type in the global namespace, however, the code fails to compile in Clang at the point Catch tries to use it, at `ReusableStringStream::operator<<`.  This happens because the SFINAE tests for insertion availability happen after `using ::operator<<`, thus the global overload is available, which activates the `Reusable`..., but when actually attempted to use them at `ReusableStringStream::operator<<` they are **not** available because:
1. there hasn't been the `using ::operator<<` at that point
2. at the namespace `Catch` there has been one overload for `operator<<(std::ostream &, SourceLineInfo const &)` that …

Fixes disagreement between `operator<<` available for SFINAE and actually usable

---

include/reporters/catch_reporter_xml.cpp
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/console.swa4.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
scripts/approvalTests.py

Xml result of reporter will now contain value of rng-seed in case it
is not zero.
The value will be stored in element Randomness and it's attribute seed.
Relates to #1402

XmlReporter: add information about rng-seed

---

include/internal/catch_session.cpp
include/internal/catch_session.h

This allows users on Windows to use Catch::Session::applyCommandLine
with wchar_t * arguments of application.
With this change Session::run became templated so both char and wchar_t
version have the same implementation.
Added convenient overload of Catch::Session::applyCommandLine on wchar_t.
With addition of this overload `Catch::Session::run` method has the same implementation for both char and wchar_t.  
User with custom main `int wmain(int argc, wchar_t * argv[])` could not use directly Catch::Session::applyCommandLine. This might have been a minor annoyance for them.
https://github.com/catchorg/Catch2/issues/1337

Session::applyCommandLine overload on wchar_t

---

contrib/CatchAddTests.cmake

Fix for issue described in #1327 
As Catch requires escape commas to find tests with commas. I've added proper command creation for test cases.
"Fixed" output will show correct test name (as before) but test will run correctly and command will include "\\," for easier manual running of the test. 
```
[...]
test 1
Start 1: Test case with a, in it
1: Test command: /home/mpatro/projects/open_source/catch_comma/mytest "Test case with a\, in it"
1: Test timeout computed to be: 1500
1: 
1: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1: mytest is a Catch v2.4.1 host application.
1: Run with -? for options
1: 
1: -------------------------------------------------------------------------------
1: Test case with a, in it
1: …
```

Fix catch_discover_tests() - should find tests with commas | Related to #1327

---

include/internal/catch_leak_detector.cpp
include/internal/catch_leak_detector.h

simple code with provided main function which just returns 0
leaks memory due to fact that singletons are not cleaned up
running valgrind on such simple application reports that 752 bytes
are still available in 11 blocks
this commit adds destructor to Catch::LeakDetector which calls
Catch::cleanUp()
There is already existing https://github.com/catchorg/Catch2/pull/1063 which added the destructor but seems to be abandoned.

Catch::LeakDetector: added cleanup call to destructor

---

include/internal/catch_commandline.cpp
include/internal/catch_list.cpp
include/internal/catch_list.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/IntrospectiveTests/CmdLine.tests.cpp

Related to #1351 
Introduced check during option parsing to validate whether reporter provided by the user is one of registered ones.
Related to #1351 
I don't know why regression didn't start

Command line parser should verify whether reporter is registered

---

contrib/ParseAndAddCatchTests.cmake
docs/cmake-integration.md

This is related to the `contrib/ParseAndAddCatchTests.cmake` script.
This is a very small but (I think) useful situational change.
This variable is set to allow the use of the nice `ParseAndAddCatchTests` script
in the case where a launcher is needed to execute  the script.
This is introduced to allow to launch unit tests using mpi. In this case one can write for instance `set(OptionalCatchTestLauncher ${MPIEXEC} ${MPIEXEC_NUMPROC_FLAG} ${NUMPROC})` before calling the `ParseAndAddCatchTests` function.
Note that the `OptionalCatchTestLauncher` is not a global CMake variable/option but is meant to be set to different values while registrating tests. In my case for instance, I register sequential unit tests as well a MPI unit tests.
Best regards,
Stéphane.

Add the optional variable OptionalCatchTestLauncher

---

include/reporters/catch_reporter_console.cpp
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/console.swa4.approved.txt

PASSED will now appear on the same line as filename and line number,
just like the case with FAILED message formatting
Minor formatting change to console reporter and unit tests output.
Closes #360

ConsoleReporter: minor formatting fix

---

docs/tostring.md

Since https://github.com/catchorg/Catch2/pull/1405 was merged and propagated to the single-include declaring a user operator<< in the global namespace makes it available to Catch2 string converters.
Many times it is not practical or legal to add overloads in the namespace of a type, for example, the namespace `std`.  However, the user may want Catch2 to be able to use their `operator<<` overloads in the global namespace.  Since the fix mentioned in pull request 1405 these overloads are available and the documentation should reflect that.

operator<< works from the global namespace

---

docs/logging.md
include/internal/catch_message.cpp
include/internal/catch_message.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Message.tests.cpp

The previous implemetation was just plain broken for most of
possible uses, the new one should work (even though it is ugly
as all hell, and should be improved ASAP).
Fixes #1436

Fix CAPTURE macro for nontrivial uses

---

.travis.yml

Deprecated `sudo: false` removed from travis config.
Removes the now deprecated option `sudo: false` from the travis config file. This is related to the current Travis Linux infrastructure migration. 
Please see the [recent Travis announcement](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) for more information.

Deprecated 'sudo: false' removed from travis config

---

.conan/build.py

- Package channel should be changed automatically when
matching the stable branch pattern
- Update Bintray upload address
- #926

#926 Fix Conan package reference

---

include/internal/catch_session.cpp

fixes errors like below
/mnt/a/yoe/build/tmp/work/aarch64-yoe-linux-musl/catch2/2.5.0-r0/git/include/internal/catch_session.cpp:52:29:
error: redundant move in return statement [-Werror=redundant-move]
52 |             return std::move(multi);
|                    ~~~~~~~~~^~~~~~~
/mnt/a/yoe/build/tmp/work/aarch64-yoe-linux-musl/catch2/2.5.0-r0/git/include/internal/catch_session.cpp:52:29:
note: remove 'std::move' call
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Remove redundant move

---

include/internal/catch_decomposer.h
include/internal/catch_meta.hpp

As explained in issue #1273, `operator&&` and `operator||` should give
a proper compile time error on use instead of the compiler complaining
about them not being defined. This PR adds an `always_false` type in
`catch_meta.hpp` used for implementing a nice `static_assert` for both
of the abovementioned operators.
Closes #1273

Add nice error messages for unsupported && and ||

---

include/internal/catch_decomposer.h

**What**
Added a static_assert for when the user is trying to perform a cascading operations like `REQUIRE(1==1==1)`
**Why**
Since Catch2's philosophy is about simple and deterministic unit testing. These complex expressions should be decomposed to smaller ones.
Currently, doing so will cause a compile error but the error message does not really describe that this is in some sense intended.
While I cannot find an issue that have this problem, doing cascading operators will fail and the error message is not nice.

Additional static asserts for cascading operators

---

include/internal/catch_type_traits.hpp

Missing `<type_traits>` include in `include/internal/catch_type_traits.hpp` is causing a compile error on Clang 6 on Ubuntu.
Issue not created

Missing <type_traits> include

---

include/internal/catch_xmlwriter.cpp

The ostream passed as reference to `hexEscapeChar` is manipulated and its original state not restored. This is an unexpected side effect and now fixed.
Seen via [coverity](https://scan.coverity.com/dashboard) in a [downstream project](https://github.com/openPMD/openPMD-api).

hexEscapeChar: restore stream

---

contrib/ParseAndAddCatchTests.cmake

When PARSE_CATCH_TESTS_ADD_TARGET_IN_TEST_NAME is enabled the cmake helper script fails to extract the testcase name if a whitespace is before the name string. Use regex to consider and remove this whitespace.
https://github.com/catchorg/Catch2/issues/1493

fix ctest output with space before name

---

include/internal/catch_timer.cpp

The clock estimator has a potential division by zero and the average is wrong on abort. Using `iteration + 1` would be correct for an average and is consistent with the non-aborted result which is also `sum / (max(i)+1)`.
Seen via [coverity](https://scan.coverity.com/dashboard) in a [downstream project](https://github.com/openPMD/openPMD-api).

ClockEstimate: Correct Average on Abort

---

docs/contributing.md

When looking into the `contributing.md`, I would’ve found it helpful to see at a glance how I can build and run the SelfTest binary correctly. This PR adds instructions for this.
Note that the instructions in this PR are what I came up with after some trial & error; if there’s a more elegant way to build the SelfTest binary I’d be more than happy to change the text accordingly :)
--

contributing.md: Add build instructions

---

docs/logging.md
examples/210-Evt-EventListeners.cpp

Add semicolon after INFO in examples

Examples: Add semicolon after INFO

---

contrib/ParseAndAddCatchTests.cmake

This PR adds the `PARSE_CATCH_TESTS_HIDDEN_TESTS_DISABLED` option to `ParseAndAddCatchTests`.
If this option is enabled and `PARSE_CATCH_TESTS_NO_HIDDEN_TESTS` option is disabled, the test is be added, but the [`DISABLED`](https://cmake.org/cmake/help/latest/prop_test/DISABLED.html) property is set, therefore CTest shows it as `Not Run (Disabled)` instead of `Passed`.
The tests that are not executed do not count in the number of executed tests.
I think this would probably be a good option to have enabled by default, but it is set it to `OFF` instead, since this would change current behaviour, and since it the option does not exist before CMake 3.9

ParseAndAddCatchTests: Add PARSE_CATCH_TESTS_HIDDEN_TESTS_DISABLED option

---

projects/SelfTest/UsageTests/ToStringVariant.tests.cpp

The behavior of libstdc++ changed on version 9 and variant isn't valueless by exception anymore on the test previously written.

fix variant test for libstdc++ version 9

---

include/internal/catch_compiler_capabilities.h

I noticed that stringification support for `std::variant` isn't activated if your compiler is gcc or clang >= 8. This should correct it.

fix variant detection with non-clang compiler

---

include/internal/catch_compiler_capabilities.h
include/internal/catch_tostring.h
projects/CMakeLists.txt
projects/SelfTest/UsageTests/ToStringOptional.tests.cpp

This commit add stringification for c++17 `std::optional`.
I used the same style than `std::variant<std::monostate>` for empty optionals (`{ }`), and no curly bracket around valid object (example: `0` or `"abc"`). See the added unit tests.
Given that this is a feature conditionally activated (if C++17 is available), then I don't know if the files modified by the script `misc/CMakeLists.txt` should be added.

Add to string for std::optional

---

include/reporters/catch_reporter_tap.hpp

According to TAP protocol version 13, the comments after the test name
only may contain Directives - # TODO or # SKIP. We should put
the comment (aka suite name) on a separate line before the test.
See http://testanything.org/tap-version-13-specification.html#directives

Fix TAP protocol reporter

---

include/catch.hpp

The REQUIRE_THROWS and CATCH_REQUIRE_THROWS macros have
a subtle inconsistency in their implementation which can
cause a warning if [-Wunused-value] is used.
This commit changes CATCH_REQUIRE_THROWS so it has the
same implementation as REQUIRE_THROWS
It looks like REQUIRE_THROWS was changed in commit
fae0fa4ec but not CHECK_REQUIRE_THROWS.
Tested on:
```
flydale-north:debug-build$ c++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
```

Catch: resolve inconsistency in CATCH_REQUIRE_THROWS

---

include/reporters/catch_reporter_bases.cpp

Some compilers don't export C compatibility functions in `::`. Using
`std::sprintf` should work for those (and all other compilers).
Reference: https://en.cppreference.com/w/cpp/header#C_compatibility_headers

use "std" namespace for "sprintf"

---

docs/opensource-users.md

In the docs I noticed some missing hyphens, so I added them. Then I noticed that some project descriptions had full-stops and others didn't. I decided to add them where missing rather than remove them if present.
N/A

Docs: missing hyphens and full-stops added

---

include/internal/catch_session.cpp

Catch 2.6.1 broke Catch integration in ReSharper C++. R++ uses a named pipe to read the output of the test binary.  A named pipe can only be opened once, but 7f229b4f caused the output file to get opened twice.
Creating a config in `Session::applyCommandLine` is actually not necessary unless there is an error to print. After this change `Session::applyCommandLine` constructs the config only when parsing of the command line arguments has failed.

Do not open the output file twice

---

include/internal/catch_capture.hpp

The issue, for some otherworldly reason, only seems to appear when using ccache, with the `-c` flag (see [relevant issue](https://github.com/ccache/ccache/issues/354)).
When compiling any test such as:
```cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
TEST_CASE("foo", "[bar]")
{
double a = 2.0;
double b = 10.0;
CHECK(a * 5.0/3.0  == b / 3.0);
}
```
Compiling it (*with ccache*):
```bash
ccache /usr/bin/clang++     -Wunreachable-code   -std=gnu++11 -c /absolute/path/test.cpp
/absolute/path/test.cpp:8:161: warning: code will never be executed [-Wunreachable-code]
} catch(...) { catchAssertionHandler.handleUnexpectedInflightException(); } catchAssertionHandler.complete(); } while( (void)0, false && static_cast<bool>( !!(a * 5.0/3.0 == b / 3.0) ) );
^
/absolute/path/test.cpp:8:130: note: …
```

fix "code will never be executed" under clang + ccache

---

include/internal/catch_interfaces_reporter.h

Clang8 warns
catch_interfaces_reporter.h:84:25: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
|         AssertionStats& operator = ( AssertionStats && )     = default;
|                         ^
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Fix -Wdefaulted-function-deleted warning

---

scripts/scriptCommon.py

Currently, the script for finding the executable is not OS aware. Specifically, it will fail to find it in Windows because the executable have .exe post-fix to its filename.
Issue #1523

fix an issue where approvalTests.py cannot find selfTest.exe executable

---

docs/generators.md
include/internal/catch_generators.hpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp

The RangeGenerator was lost during the refactor of the generator interface. I've re-implemented it using the new generator interface. I have also extended it by adding an optional step size.
If it is satisfactory then I will update the documentation as well.
Disappeared in #1516

Reimplementing RangeGenerator

---

docs/logging.md
include/catch.hpp
include/internal/catch_capture.hpp
include/internal/catch_interfaces_capture.h
include/internal/catch_message.cpp
include/internal/catch_message.h
include/internal/catch_run_context.cpp
include/internal/catch_run_context.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Message.tests.cpp

Add assertion scoped information messaging functionality. Newly introduced `ASSERTION_INFO` macro stores messages kept until next assertion expression, that is, they are cleared right until after `assertionEnd` every time. This enables passing info message across helper functions in assertion scope, which is not allowed currently due to local scope of `INFO` macro.
If this looks reasonable, I will go ahead and add complementary `SECTION_INFO` and `TEST_CASE_INFO` macros following the same logic for sections and test cases respectively.
I've added a few test cases and updated approval tests accordingly. Please verify correctness of approval tests. They looked good to me.
Related to #415, #983.

Unscoped info feature

---

docs/matchers.md

Because `Catch::MatcherBase<T>::describe()` is virtual method, when someone copy-paste this example code for changing, typically code-analyzer produces warning about [`IntRange::describe()`](https://github.com/catchorg/Catch2/blob/master/docs/matchers.md#custom-matchers) `override`ing.

Added override keyword near IntRange::describe() method

---

docs/generators.md

This is a trivial change to remove an extraneous back tick character in [generators.md](https://github.com/catchorg/Catch2/blob/master/docs/generators.md). 
This is present in (Data Generators / Provided generators / For safety reasons, ...). See the code block with `TEST_CASE("type conversion"`, end of line 2.

generators.md: fix extraneous back tick in doc

---

docs/opensource-users.md

Added raspigcd to the opensource-users that uses Catch2 for tests
I would like to include my little project (described here https://hackaday.com/2018/05/15/direct-cnc-control-with-the-raspberry-pi/) in the list of usages of Your awesome test lib. Raspigcd uses older version of Catch. The new version (not yet mentioned here) will use Catch2.

raspigcd - opensource-users

---

include/internal/catch_fatal_condition.cpp

*Windows-specific*
EXCEPTION_* codes are typically mapped to corresponding STATUS_* codes, e.g.
`#define EXCEPTION_INT_DIVIDE_BY_ZERO        STATUS_INTEGER_DIVIDE_BY_ZERO`
STATUS_* codes are *typically* defined in winnt.h:
`#define STATUS_INTEGER_DIVIDE_BY_ZERO    ((DWORD   )0xC0000094L)`
However, winnt.h defines only a limited subset of them, and sometimes it might be desirable to access the full set from ntstatus.h. A simple inclusion of ntstatus.h causes a lot of warnings because these constants are now defined twice. The conventional approach is to definine `WIN32_NO_STATUS` before including windows.h and undefine it before including ntstatus.h.
For some reason in ntstatus.h these constants are defined in a slightly different way:
`#define STATUS_INTEGER_DIVIDE_BY_ZERO …

Suppress warning caused by ntstatus.h inclusion

---

docs/generators.md
include/internal/catch_generators.hpp
include/internal/catch_generators_generic.hpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp
projects/SelfTest/UsageTests/Generators.tests.cpp

`map` generator helper function requires its return type to be given explicitly if it is different from the type produced by the generator argument. This patch enables deducing the return type from the return type of given lambda function. Example: 
This:
```c++
auto val = GENERATE(map<std::tuple<int, std::string>>([](int val) {
return std::make_tuple(val, std::to_string(val));
}, range(-5, 5));
```
can be optionally written as:
```c++
auto val = GENERATE(map([](int val) {
return std::make_tuple(val, std::to_string(val));
}, range(-5, 5));
```

Deducing return type of map generator helper

---

include/internal/catch_config.hpp
include/internal/catch_interfaces_config.h
include/reporters/catch_reporter_bases.cpp
include/reporters/catch_reporter_bases.hpp
include/reporters/catch_reporter_console.cpp
include/reporters/catch_reporter_console.h
include/reporters/catch_reporter_junit.cpp
include/reporters/catch_reporter_xml.cpp
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/console.swa4.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt

Adding printing of the filters being used by the tests as part of the report.
Example Console Reporter:
Example XML Reporter:
Example JUnit Reporter:
When running the tests from a non terminal interface like any IDE, the arguments passed to main are hidden under a pile of GUI and usually you don't look at them before running the executable.
If you forger that you've added a filter to the tests, you might think that all your test have passed and commit new changes, but some of the tests did not even run, and you can miss it in case the number of tests that have passed is close enough to the total number of tests/assertions (or you simply don't know how many assertions should pass). 
Having a bright yellow indication of filters that were in use makes the report more complete and also helps …

Support for printing test filters

---

docs/cmake-integration.md

The header at https://github.com/catchorg/Catch2/blob/master/docs/cmake-integration.md#catchcmake-and-addcatchtestscmake should be naming https://github.com/catchorg/Catch2/blob/master/contrib/CatchAddTests.cmake

Use correct filename in CMake integration docs

---

contrib/ParseAndAddCatchTests.cmake

Drop `list(FIND Labels "!hide" IndexOfHideLabel)` due to it's return value `IndexOfHideLabel` is never used. So the find in the list is unnecessary.

IndexOfHideLabel is never used

---

.conan/build.py
.github/pull_request_template.md
CMake/FindGcov.cmake
CMake/Findcodecov.cmake
docs/command-line.md
docs/configuration.md
docs/logging.md
docs/other-macros.md
docs/release-notes.md
docs/release-process.md
include/internal/catch_matchers_generic.hpp
include/internal/catch_output_redirect.cpp
include/internal/catch_test_case_info.cpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/ToStringGeneral.tests.cpp
projects/XCode/OCTest/OCTest/CatchOCTestCase.mm

Fixed typos identified by Codespell in source code as well as associated test data. Done because I run codespell in CI on a project that is starting to vendor Catch2, which pointed out the typos.
Builds and tests complete successfully on Debian Buster.

Fix typos identified by codespell.

---

include/internal/catch_debugger.cpp

Catch2 was not able to compile with GCC or Clang on macOS.
This is done by forcing isDebuggerActive() to `false` when building Catch2 on macOS with Clang or GCC. When building with AppleClang, isDebuggerActive() will function as before.
Closes #1588

Fix macOS Clang and GCC build on macOS

---

contrib/ParseAndAddCatchTests.cmake

A few enhancements to the `ParseAndAddCatchTests` CMake module:
After the script, the `ParseAndAddCatchTests_TESTS` property for the target, and for each source file in the target is set, and contains the list of the tests extracted from that target, or from that file.
This is useful, for example to add further labels or properties to the tests.
When using an optional launcher the target name is not interpreted as a target, therefore it is not replaced automatically with its path.

 ParseAndAddCatchTests enhancements

---

contrib/CatchAddTests.cmake

- `ctest --print-labels` now will show list of available labels
- `ctest -L <regex>` will allow to run tests with given labels(tags)
Having an executable with given list of tests:
```
> exercises/ut/exercisesTests --list-tests
All available test cases:
Life, the universe and everything
Having fun with lambdas
[cpp11][lambdas]
Delegating constructors
[constructor][cpp11][delegation]
User-defined literals functionality
Class modifications introduces in C++11
[cpp11][default][delete][final][override]
5 test cases
```
`catch_discover_tests` now discovers correctly:
```
ctest -N
Test project /home/mpatro/projects/clion/self_learn_repo/cmake-build-debug
Test #1: Life, the universe and everything
Test #2: Having fun with lambdas
Test #3: Delegating constructors
Test #4: User-defined literals …
```

CatchAddTests now adds tags as labels for ctest

---

contrib/ParseAndAddCatchTests.cmake

This PR will make the ParseAndAddCatchTests function ignore any "files" that match `\$<TARGET_OBJECTS:.+>`, so when you use cmake object libraries the script will not try to parse that "file" for the Catch2 TEST_CASE macros.
I am putting file in quotes here because in the case of object libraries this is clearly a cmake variable and not a file.
I am using a cmake object library to compile the sources of my target binary and re-use them in my Catch2 unittests without recompiling them.
```
add_executable(mytest $<TARGET_OBJECTS:myobj> test_main.cc test1.cc test2.cc)
target_link_libraries(mytest Catch2::Catch2)
include(CTest)
include(ParseAndAddCatchTests)
ParseAndAddCatchTests(mytest)
```
This will give the following warnings (PARSE_CATCH_TESTS_VERBOSE is set during cmake configuration)
``` …
```

ParseAndAddCatchTests: Ignore cmake object libraries

---

docs/event-listeners.md
docs/matchers.md
examples/210-Evt-EventListeners.cpp
include/internal/catch_config.hpp
include/internal/catch_console_colour.cpp
include/internal/catch_context.cpp
include/internal/catch_exception_translator_registry.h
include/internal/catch_reporter_registrars.hpp
include/internal/catch_test_spec.h

In C++, `override` implies `virtual`.
Another reference on SO:
https://stackoverflow.com/questions/43466863/isnt-virtual-keyword-redundant-when-override-or-final-specifiers-are-used
Detected via CodeFactor.io score in a downstream project: https://github.com/openPMD/openPMD-api/pull/293

Refactor: override implies virtual

---

include/internal/catch_approx.cpp
projects/SelfTest/UsageTests/Message.tests.cpp

I was playing with Catch2 locally and my default set of cxxflags caused build errors, specifically `-Wshadow` (tested with gcc-7.3.0).  This change just renames a few function parameters to avoid the shadowing.
```
[/tmp/catch2/build] cmake ../source/ '-DCMAKE_CXX_FLAGS=-Wall -Wextra -Wshadow -pedantic' -GNinja
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.6.5") 
-- Enabling C++11
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/catch2/build …
```

Fix warnings generated with -Wshadow

---

include/internal/catch_matchers_vector.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Matchers.tests.cpp

In addition to Equals and UnorderedEquals, this PR implements an Approx matcher for std::vector<T>.
It is implemented along the lines of Equals and UnorderedEquals, with inspiration from previous attempts in issue #760, and [this StackOverflow discussion](https://stackoverflow.com/questions/41160846/test-floating-point-stdvector-with-c-catch)
Addresses #760

Vector Approx matcher

---

include/internal/catch_test_case_tracker.cpp
include/internal/catch_test_case_tracker.h
projects/SelfTest/IntrospectiveTests/PartTracker.tests.cpp

TrackerContext is not used as singleton, so just remove this misleading method.
While working on an prove of concept for something in catch, I was confused by this no longer needed method leading me to think that TrackerContext was a singleton. But it's not.

TrackerContext: Remove misleading instance static method.

---

docs/slow-compiles.md

the example  in docs/slow-compiles.md miss to link factorial.o file which lead to an undefined reference error.
I don't find relevent issue and hope I don't get it wrong with cpp's linker.

fix  example's mistake in  slow-compiles.md

---

include/internal/catch_message.cpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Message.tests.cpp

Simple fix to allow CAPTURE to handle string with comma. Also ignores
brackets in string. No quotation mark escaping is implemented, so `"\""`
and `'"'` will still fail.
Fixes #1607 
I can improve parsing algorithm to handle single and double quotes correctly, but that is probably overkill ...

Allow quotes in CAPTURE arguments

---

docs/tostring.md
include/internal/catch_tostring.cpp
include/internal/catch_tostring.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/ToStringGeneral.tests.cpp

Per #1612, this change allows the user to set custom precision on floating-point test messages. I did implement the unit test gestured at in the issue, but I'm not sure if you want it.
Closes #1612.

Allow custom precision in error reports for floating-point numbers

---

include/catch.hpp
projects/ExtraTests/X01-PrefixedMacros.cpp

The new `UNSCOPED_INFO` feature was only added for the default usage. This adds defines so that it works under `#define CATCH_CONFIG_PREFIX_ALL` and/or `#define CATCH_CONFIG_DISABLE`.
The `X02-DisabledMacros.cpp` is pretty thin and doesn't test individual macros, so only the `CATCH_`-prefixed modification is accounted for in tests. Expanding that test seemed out scope for this PR, but I'm happy to be the first if that's useful.
Amends #1522, which introduced `UNSCOPED_INFO`

Add UNSCOPED_INFO to prefix/disabled sections

---

include/internal/catch_console_colour.cpp

On different windows virtual machines test executables with Catch2 would crash with a segmentation fault.
The reason is that the `platfomColourInstance()` in `Colour::use()` would return a null-ptr. This will not be checked and thus a c000000005 will happen.
I created this simple PR to check for the null-ptr and avoid calling `impl->use( _colourCode );`
The result is that the tests won't crash anymore, but the downside is that the console output is not coloured anymore. So it is just a workaround.
Probably related: #1626

Fixed a bug where the application would die due to a null-ptr of platformColourInstance

---

contrib/CatchAddTests.cmake

Fixes #1645 by rolling back d4eec016a9df54a560d82e5ee12aef42822525e7 ; reopens #1590 .
Parsing `--list-tests` is broken, as Catch automatically line wraps the line when it gets too long, stripping any whitespace in the process. This means that it's impossible to reproduce the exact name of the
test if the test's name is long enough to line-wrap.
Furthermore, overwriting the `LABELS` property with the discovered labels breaks users who manually added custom ctest labels. However, this seems to not actually overwrite the labels due to buggy handling of our strange test names by CMake.
Rolling back to using `--list-test-names-only` for now, as it does not wrap lines even on very long test names.
We may be able parse the output of `--list-tags` to produce the ctest labels. However, the …

Fix catch_discover_tests() from breaking on long test names

---

include/internal/catch_test_case_tracker.cpp
projects/CMakeLists.txt
projects/SelfTest/IntrospectiveTests/PartTracker.tests.cpp

The function now verifies that all children have completed, instead of only the last. This fixes the section exeuction bug I reported the other day.
Fixes #1670.

Fix TrackerBase::close children completion check

---

include/internal/catch_generators_generic.hpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Generators.tests.cpp

Make ChunkGenerator always return empty vectors when chunk-size is 0.
Fixes #1671

Fix ChunkGenerator with chunk-size 0

---

docs/command-line.md
docs/contributing.md

I ran `updateDocumentToC.py` to update the Contents lists.
Only two files changed:
* docs\command-line.md: updated the names of two sections in the Contents
* docs\contributing.md: this added a missing Contents list, but did not create the `<a id="..."></a>` lines
Can I check I understand? Does the ToC script require a human to also manually add or update the `<a id="..."></a>` lines - or do they not matter, when viewing via the github website?
This is just me seeing how the script to update the Contents lists works, and making sure I can submit PRs from my fork - before working on #1667

Update Contents in docs #1667

---

include/internal/catch_compiler_capabilities.h
include/internal/catch_tostring.cpp
include/internal/catch_tostring.h
projects/CMakeLists.txt
projects/SelfTest/UsageTests/ToStringByte.tests.cpp

This addresses issue #1685, adding a `std::byte` specialisation for `Catch::Detail::StringMaker`, which makes `std::byte` print as an integer rather than as a character.
This has three parts:
1. **Add byte detection in Catch config**
Following the pattern used for `std::optional`, look for the include file `cstddef` and the macro `CATCH_CPP17_OR_GREATER`. This defines `CATCH_INTERNAL_CONFIG_CPP17_BYTE`, which may then cause `CATCH_CONFIG_CPP17_BYTE` to be defined.
2. **Add a `std::byte`specialisation for Catch2::Detail::StringMaker**
Added a declaration (gated by `CATCH_CONFIG_CPP17_BYTE`) of `struct StringMaker<std::byte>` in `catch_tostring.h`, and a definition in `catch_tostring.cpp`.
3. **Added a self-test (only compiled & executed for c++17)**
Added new file …

Add `std::byte` support

---

docs/release-notes.md

Hi, there was a trivial typo in the notes for 2.7.1 release, which this fixes:
GENERATE_VAR -> GENERATE_REF
This removes the only instance in code of that typo.
Is it possible to make the same edit here:
https://github.com/catchorg/Catch2/releases/tag/v2.7.1

Fix typo in 2.7.1 release notes

---

include/internal/catch_test_registry.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Misc.tests.cpp

std::tuple is not default constructible when the first type is not
default-constuctible. Therefore it can not be instantiated.
To circumvent this, we have to use std::declval in the unevaluate decltype
context.

Fix non-default-constructible type lists used in TEMPLATE_LIST_TEST_CASE

---

contrib/CatchAddTests.cmake

The issue was that square brackets are in principle legal in the name of a test case, but CatchAddTests was passing them directly to the test executable, which interprets them as a tag. It now escapes these brackets along with commas in test case names.
Fixes #1634.

Fix CTest command issue with square brackets

---

include/reporters/catch_reporter_xml.cpp
include/reporters/catch_reporter_xml.h

When running a benchmark, that throws an exception or a optimized away exception is thrown, the xml reporter closes the wrong tag.
This was fixed by opening a BenchmarkResults tag on the preparing message. This way it is also reproducible, which benchmark failed.

Fix xml reporter crashing when a benchmark failed.

---

include/internal/catch_debug_console.cpp

Adds an implementation of `writeToDebugConsole` for Android that logs directly to Logcat.
In my opinion, this provides a really good out-of-the-box experience for Android NDK developers.
I refrained from adding `CATCH_PLATFORM_ANDROID` and a `catch_android_h_proxy.h` as this felt a little heavy considering that the platform is really more Linux-like and the change is very focused. Happy to make any changes suggested though 😄

Add Android implementation of writeToDebugConsole that prints to Logcat

---

docs/benchmarks.md
docs/command-line.md
docs/configuration.md
docs/generators.md
docs/logging.md
docs/other-macros.md
docs/test-cases-and-sections.md
docs/test-fixtures.md
docs/tostring.md
scripts/extractFeaturesFromReleaseNotes.py

**This is a work-in-progress - more changes coming later**
Add a mechanism - `scripts/extractFeaturesFromReleaseNotes.py` to generate text for pasting in to docs/*.md, to indicate the release number in which recent features were added.
Partial implementation of this part of #1667 
> For recently-added features, add "Introduced in Catch 2.x.y" to the documentation - see https://docs.gitlab.com/ee/ci/variables/#variable-types for an example
So far, I've just added the text 'Introduced in Catch 2.9.0.' - to get feedback on whether this is the kind of thing you expected, @horenmar ...
After initial feedback, I'll fill in the text for more releases.

Add 'Introduced in Catch 2...' to docs, for recent Catch releases

---

include/internal/catch_interfaces_testcase.h
include/internal/catch_session.cpp
include/internal/catch_test_case_registry_impl.cpp
include/internal/catch_test_case_registry_impl.h
include/internal/catch_test_spec.cpp
include/internal/catch_test_spec.h
include/internal/catch_test_spec_parser.cpp
include/internal/catch_test_spec_parser.h
projects/CMakeLists.txt
projects/SelfTest/WarnAboutNoTests.cmake

This PR is for two issues related to filtering tests, reported in issue #1449.
It modifies various existing structures to allow checking whether any filters passed to a test executable did not result in any matching test cases, giving the user better feedback about the input. It also adds small helper classes to aid readability of the code. Additionally, the option `-w NoTests` is now correctly checked and an exit code 2 returned if there were any unmatched filters.
Fixes #1449. Also fixes #1683.

Improve reporting of unmatched filters

---

include/reporters/catch_reporter_compact.cpp

I was playing with different reporters and found an infinite loop when using the compact reporter with no further options. This is fixed by ensuring that the message iterator is always advanced in the `printRemainingMessages` function.

Fix infinite loop in compact reporter printer

---

include/internal/catch_fatal_condition.cpp

Seen with PGI compiler for `static constexpr`:
```
warning: storage class is not first
```
N/A

static constexpr: storage class first

---

include/internal/catch_tostring.h

Closes #1722
This PR fixes a compilation issue on Solaris 11.4 with GCC 7.3.0 on the latest Catch2 master branch. A #define in the Solaris 11.4 <sys/regset.h> header conflicts with a template parameter name used in catch_tostring.h and it gets renamed to an integer constant. This causes an obvious compilation issue. Please refer to the issue for more details about the bug.
The bug is simply fixed by re-naming the 'SS' template parameter name to something more descriptive like 'Stream'. I also took the liberty of renaming the template parameter name 'TT' to 'U' because I saw the template parameter name 'U' used throughout the codebase and couldn't find any other "same double letter" names used.
After making this change, I can confirm that Catch2 compiles and builds with the main.cpp file …

Rename template parameter names to avoid name conflict on Solaris.

---

include/internal/catch_compiler_capabilities.h

Fix the test for MSVC version: variadic macros support is available
since MSVS 2005, a.k.a. MSVC 8, using _MSC_VER=1400.
---
I know nobody cares about this ancient compiler any more, but unfortunately I still have to build some projects using it, and I'd still like to use CATCH with it and it does support variadic macros.

Enable variadic macros support for MSVS 2005 as it has them

---

include/internal/catch_preprocessor.hpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Misc.tests.cpp

This is a follow-up to #1697.
The parameter given to `convert` may not be copyable therefore it has to be
captured by const reference. For example an `std::tuple` that contains a
non-copyable type is itself non-copyable.
The NonDefaultConstructible test-case was reduced by one example type
because it did not add any value.

Allow to use non-copyable and non-movable types in TEMPLATE_LIST_TEST_CASE

---

include/internal/catch_interfaces_config.cpp
include/internal/catch_interfaces_exception.cpp
include/internal/catch_interfaces_registry_hub.cpp
include/internal/catch_interfaces_runner.cpp
include/internal/catch_interfaces_testcase.cpp
include/reporters/catch_reporter_compact.cpp
include/reporters/catch_reporter_console.cpp

Updated some include directives to improve consistency and add more flexibility when integrating Catch2 with regard to include directories (e.g., allows setting the root as include directory).

Small updates to include directives

---

include/internal/catch_test_spec_parser.cpp
include/internal/catch_test_spec_parser.h
misc/coverage-helper.cpp
projects/CMakeLists.txt
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/IntrospectiveTests/CmdLine.tests.cpp

In Catch v2.9.2 escape characters are not working properly
I modified the finite state machine implemented in include/catch_test_spec_parser.cpp
to correct this problem
Issue #1737

Escape characters bug patch(v2.9.2)

---

docs/opensource-users.md

Add Cataclysm: Dark Days Ahead to projects list.
I'm the project owner.
Thanks so much for writing Catch2.
None

Add Cataclysm:Dark Days Ahead to project list

---

include/reporters/catch_reporter_console.cpp

Removed unused informations from benchmarks output when --benchmark-no-analysis flag is used to improve readability.

Simplified benchmark output with --benchmark-no-analysis

---

include/internal/catch_test_spec_parser.cpp
include/internal/catch_test_spec_parser.h
projects/CMakeLists.txt
projects/SelfTest/Misc/plain-old-tests.input
projects/SelfTest/Misc/special-characters-in-file.input

When Catch parses quoted test name, it may insert wrong positions of escape characters into
TestSpecParser::m_escapeChars, because the quotes are not added to the pattern itself
I added a simple data member to TestSpecParser that will track the right location of those characters in the pattern.
This PR resolves Issue #1767

Patch:Failure to pass special chars through input file

---

docs/contributing.md

Going through the documentation to get started with some bug fixes, I noticed that with using Visual Studio as CMake generator leads to errors when trying to run ctest exactly as described in the documentation.

add a note how to run selftests using multiconfig generators

---

include/internal/catch_commandline.cpp
include/internal/catch_interfaces_reporter.h
include/internal/catch_session.cpp
include/internal/catch_test_spec.cpp
include/internal/catch_test_spec.h
include/internal/catch_test_spec_parser.cpp
include/internal/catch_test_spec_parser.h
include/reporters/catch_reporter_bases.hpp
include/reporters/catch_reporter_console.cpp
include/reporters/catch_reporter_console.h
include/reporters/catch_reporter_listening.cpp
include/reporters/catch_reporter_listening.h

Catch 2.9.2 lacks the means to detect invalid test names and ignore them when needed.
This PR resolves Issue #1766

Patch: Catch terminates when parsing invalid test name from input file

---

include/internal/catch_context.h

Fixes issue #1230
Suppress a false positive warning from the Clang static analysis tools which thought that a null reference was potentially being returned here.

Suppress false positive from clang-analyzer

---

docs/command-line.md

I've been searching for a way to run all tests from a file for some time. To avoid other users having to connect the dots of tags and the `-#` option add a simple example to the "Specifying which tests to run" section.

docs: command-line: Add example to specify tests by file name.

---

include/reporters/catch_reporter_junit.cpp
projects/SelfTest/Baselines/junit.sw.approved.txt

The JUnit report is improved in that:
* The message shows the testing condition, not the result
* The actual message has similar output than the console one
My reason is that using catch2 with junit reporter in a gitlab testing environment, failures report next to nothing, just the line where the failure happened. So i modified the output to be similar to the console one.
I think this also addresses #1347

Improve JUnit failure report

---

include/internal/benchmark/catch_benchmark.hpp

On systems where std::chrono::steady_clock::period is not std::nano, benchmark tests fail to compile due to trying to convert analysis.samples from a vector of duration<double, clock::period> to a vector of std::chrono::duration<double, std::nano>.
To fix this, we instead construct a BenchmarkStats that matches the period of the clock. Once it's constructed, BenchmarkStats's conversion operator will handle converting to other durations.

Fix error when period of steady_clock is not nano

---

docs/benchmarks.md
include/internal/benchmark/catch_constructor.hpp
projects/SelfTest/UsageTests/Benchmark.tests.cpp
scripts/generateSingleHeader.py

This PR addresses a couple of things from #1800 
1. Add a warning to generateSingleHeaders.py to indicate that a header wasn't parsed as part of generating the single header. This would have alerted devs to the fact that catch_constructor.hpp was not part of the single header.
2. Correct docs/benchmarks.md usage of BENCHMARK_ADVANCED for the "construct" and "destroy" examples. The original documentation would not have compiled as written.
3. Correct the namespacing on helpers and constructs in catch_constructor.hpp. The docs indicated that these were intended to be found in the Catch::Benchmark namespace.
Motivated by #1800 even though it is already closed.

Update single header generation script to warn about unused headers

---

include/internal/catch_generators.hpp
projects/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp

Fix SingleValueGenerator CTor clash. Correct some misuses of move when forward was needed. Correct some missing universal references in method parameter lists. Add IntrospectiveTest to verify fix for issue #1809.
SingleValueGenerator had 2 clashing CTors thanks to the semantic differences in universal references and rvalue references when used in templates as parameters. 
Closes #1809

Fix issue #1809.

---

include/internal/catch_console_colour.cpp
include/internal/catch_debugger.cpp
include/internal/catch_debugger.h

iOS break into debugger

---

include/internal/benchmark/detail/catch_stats.hpp

**Fixes**: C2760	syntax error: unexpected token '>', expected 'expression' internal\benchmark\detail\catch_stats.hpp 69:
`std::uniform_int_distribution<decltype(n)> dist(0, n - 1);`
for a static library with `CATCH_CONFIG_ENABLE_BENCHMARKING` in Visual Studio 2019 16.4.2 (latest non-preview).

Added <random> include for std::uniform_int_distribution

---

conanfile.py

Updated conanfile for v3. It uses the static library build, not the single header.
_:question: Is the target branch (`dev-v3`) the right one for *v3* contributions?_
#1823, #1830

Conanfile updated for v3

---

include/internal/catch_xmlwriter.cpp

Catch2 was conflicting with my code that had a "#define uchar unsigned char" in its code. I found that Catch2's use of "uchar" was extremely limited (one "using uchar = unsigned char", two subsequent uses of "uchar"). Under the principle that Catch2 should be as light on the land as possible, I edited the three lines involved, re-ran the Catch2 SelfTests (it not surprisingly passed) and created this PR.
None

Removed unneeded 'using uchar = unsigned char'

---

docs/configuration.md
include/internal/catch_debugger.h

Unfortunately, the project I work on supports platforms under NDA, and so I can't upstream the fixes here.
(It'd be really nice if all platform configuration macros like this were externally configurable! But just this one is the one we need right now.)

Make CATCH_BREAK_INTO_DEBUGGER be user-configurable

---

docs/command-line.md
docs/configuration.md
include/internal/benchmark/catch_benchmark.hpp
include/internal/catch_commandline.cpp
include/internal/catch_config.cpp
include/internal/catch_config.hpp
include/internal/catch_debugger.h
include/internal/catch_interfaces_config.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/sonarqube.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/IntrospectiveTests/CmdLine.tests.cpp

There's a constant, `warmup_time`, that is used for both timer statistics discovery, as well as test warmup. The timer statistics usage is fine, but, the default constant of 100ms used for each and every test warmup makes running a large number of benchmarks take an unreasonable amount of time (the project I'm working on has many very small/fast benchmarks).
This PR makes that constant be configurable with a command line switch, instead of a `const`.
Thanks! :sparkles:

Make warmup_time be configurable

---

src/catch2/catch_decomposer.h

Fixes the pragma, causing an unknown pragma warning on GCC.
#1856

v3: GCC pragma fix

---

include/internal/catch_compiler_capabilities.h
include/internal/catch_matchers_floating.cpp

C++11 math requires _GLIBCXX_USE_C99_MATH_TR1 to be true with gcc/clang.
Also fixes an issue with uClibc-ng where __UCLIBC__ is defined in features.h but
that is not included here and is thus no-op.
Similar to how boost does it: https://github.com/boostorg/math/blob/5f8561bcfd4f1784e729acd333d3532e30adc477/include/boost/math/tools/roots.hpp#L863

catch_compiler_capabilities.h: use proper math define

---

docs/command-line.md
include/internal/catch_commandline.cpp
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/sonarqube.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/IntrospectiveTests/CmdLine.tests.cpp

I want my end-users on Windows to be able to run the tests without navigating to the folder on the command-line and view the results before the Window closes, so I set the default value for the option in the config runner:
``` cpp
session.configData().waitForKeypress = Catch::WaitForKeypress::BeforeExit;
```
On the CI systems, I can't wait for a keypress so I'd like to disabled the prompt by adding `--wait-for-keypress never` to the command line.

Add command line option 'never' to --wait-for-keypress

---

include/internal/benchmark/detail/catch_stats.hpp

Needed for `std::back_inserter` on some platforms (in particular, windows) when building `catch_stats.cpp`.

include <iterator> in catch_stats.hpp

---

include/reporters/catch_reporter_console.cpp
include/reporters/catch_reporter_xml.cpp

I mostly care about `catch_reporter_xml.cpp`, but, figured I'd also do `catch_reporter_console.cpp` while I'm in the area.
Also, some context, since it's not plainly visible in the diff - stdev (just below) is already being written as doubles, without casting to int, so I don't think there's an issue with mean being written as a double as well

Don't cast nanoseconds to integers when writing output

---

include/reporters/catch_reporter_console.cpp

After printing the list of filters, switch back from yellow to black before printing a newline to avoid the remaining output to be colored in yellow.
This is especially useful when the output is prefixed. In [Fawkes](https://github.com/fawkesrobotics/fawkes/), our build system prepends the test output with `[TEST]`, which is colored incorrectly:
old:
with this PR:
This is a purely aesthetic change, but I found it annoying enough to want it to be fixed.

Switch back to uncolored output after printing filters

---

include/reporters/catch_reporter_console.cpp
projects/ExtraTests/CMakeLists.txt

The width for the "benchmark name" column in full analysis mode is too large, which makes the output spill beyond `CATCH_CONFIG_CONSOLE_WIDTH`. 
The width was set to `CATCH_CONFIG_CONSOLE_WIDTH - 32`, but the other three columns are each 14 wide, for a total of 42, not 32, thus giving a total line length of `CATCH_CONFIG_CONSOLE_WIDTH + 10`, when it should obviously not exceed `CATCH_CONFIG_CONSOLE_WIDTH`. (My guess is that `32` was a typo for `42`.)
The best solution I see is setting the width of the "benchmark name" column to `CATCH_CONFIG_CONSOLE_WIDTH - 43`, the same as it is in the no analysis case. This PR does that.
Fixes #1885.

Fixed typo in "benchmark name" column width calculation.

---

docs/opensource-users.md

Updating documentation of open-source projects using Catch2:
- Fixed alphabetical ordering
- Added an additional project ([toml++](https://github.com/marzer/tomlplusplus))
Not related to any specific issue.

Updating documentation of open-source projects using Catch2

---

docs/cmake-integration.md

Catch2 is available as a port in VCPKG , documenting the install process here will help users get started by providing a single set of commands to build Catch2, ready to be included in their projects.
VCPKG is a C++ library manager that simplifies installation for Catch2 and other project dependencies, we also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.

Add vcpkg installation instructions

---

include/internal/catch_compiler_capabilities.h

`CATCH_INTERNAL_IGNORE_BUT_WARN()` introduced with b7b346c (*) triggers clang-tidy warning [cppcoreguidelines-pro-type-vararg](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-vararg.html) for every usage of assertion macros like `CHECK()` and `REQUIRE()`. Silence it via `NOLINT` in the `#if defined(__clang__)` block only, as clang-tidy honors those.
(*) Thanks for that one BTW, uncovered a few warnings in our test code.
n/a (decided to try to file PR instead of creating a ticket)

Suppress clang-tidy warning about vararg usage in assertion macros

---

include/internal/catch_compiler_capabilities.h

This change eliminates use of the `__builtin_constant_p` intrinsic for IBM XL compilers that use the clang front end. Under XL, code is generated to call destructors for temporaries in expressions passed to `__builtin_constant_p`, but the code to initialize those temporaries is not emitted. For example, IBM XL will generate a call to `std::string::~string` for the following code:
```c++
__builtin_constant_p(std::string("12") + "34");
```
This often results in a segfault in the case of `std::string::~string`, as `free` will likely be called on an invalid address.
Concretely, this code would result in a segfault:
```c++
REQUIRE(std::string("12") + "34" == "1234");
```
Previously, this the tests would fail when building with IBM XL 16.1.1.7. Now they all pass.
The bug has been reported to …

Remove usage of __builtin_constant_p under IBM XL

---

include/internal/catch_test_case_registry_impl.cpp
projects/CMakeLists.txt
projects/TestScripts/testRandomOrder.py

Previously a random test ordering was obtained by applying `std::shuffle` to the tests in declaration order.  This has two problems:
- It depends on the declaration order, so the order in which the tests will be run will be platform-specific.
- When trying to debug accidental inter-test dependencies, it is helpful to be able to find a minimal subset of tests which exhibits the issue. However, any change to the set of tests being run will completely change the test ordering, making it difficult or impossible to reduce the set of tests being run in any reasonably efficient manner.
Therefore, change the randomization approach to resolve both these issues.
Generate a random value based on the user-provided RNG seed.  Convert every test case to an integer by hashing a combination of that value …

Change random test shuffling technique

---

include/internal/catch_compiler_capabilities.h

Catch assumes std::uncaught_exceptions is available whenever C++17 is
available, but for macOS versions older than 10.12 this is not the case.
Instead of checking the C++ version, use a macro to check whether the
feature is available.

Use macro to determine whether std::uncaught_exceptions is available

---

include/internal/catch_matchers_vector.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/UsageTests/Matchers.tests.cpp

This PR allows to use `std::vector` with custom allocator (e.g. `Eigen::aligned_allocator`) in vector Matchers.
For `VectorContains`, the allocator must be specified explicitly since it cannot be deduced from the comparator. For the other Matchers, it's deduced from the comparator, but may also be specified explicitly in case the allocator differs between comparator and matched object.

support custom allocators in vector Matchers

---

include/internal/catch_assertionhandler.cpp
include/internal/catch_interfaces_exception.h

Tested by building our program that consumes Catch2 with `-fno-exceptions`.
The #include change is a little abstract, so to be clear, this is the line that was failing to build (with `CATCH_ERROR not found`) https://github.com/catchorg/Catch2/blob/37cbf4a4fe7a2963f8ae6d6fe998f8ac9360cbc0/include/internal/catch_assertionhandler.cpp#L88

Fix build with CATCH_CONFIG_DISABLE_EXCEPTIONS enabled

---

conanfile.py

To make things simple I aim to do:
```
find_package(Catch2 REQUIRED)
include(CTest)
include(Catch)
add_executable(example_tests tests.cpp)
target_link_libraries(example_tests Catch2::Catch2)
catch_discover_tests(example_tests)
```
Using conan's cmake_find_package generator. But `Catch.cmake` can't be found. This commit fixes the conan package.

Provide path of the cmake scripts to conan

---

include/internal/catch_message.cpp

```
D:\vcpkg\toolsrc\include\catch2\catch.hpp(11285): warning C6330: 'char' passed as _Param_(1) when 'unsigned char' is required in call to 'isspace'.
D:\vcpkg\toolsrc\include\catch2\catch.hpp(11288): warning C6330: 'char' passed as _Param_(1) when 'unsigned char' is required in call to 'isspace'.
```
ISO/IEC 9899:2011:
"7.4 Character handling <ctype.h>"/1
[...] In all cases the argument is an int, the value of which shall be
representable as an unsigned char or shall equal the value of the macro
EOF. If the argument has any other value, the behavior is undefined.
This means if isspace was passed a character like ñ it could corrupt
memory without the static_cast to treat it as a positive value after
integral promotion (and C libraries commonly use the int index supplied
as a key into a …

Fix invalid isspace call detected by PREfast

---

include/internal/catch_tostring.h

Sorry for my poor English, I'm not a native speaker.
The failure case is published on https://wandbox.org/permlink/E3IuG3dbqTTDAwxv
Which can be fixed by this patch as https://wandbox.org/permlink/jDqVGe2TlJ8F3Q9r
This bug is caused by std::__detail::begin declared by bits/iterator_concepts.h, the function may be lookup by adl, like the case above, so here will be a matched but deleted begin, not the begin returning not_this_one
This patch fixed the bug by detecting whether expression begin(std::declval<T>()) is well-formed directly
The void_type is introduced because of issue mentioned [here](https://en.cppreference.com/w/cpp/types/void_t#Notes)

Fix compilation failure when using libstdc++10

---

.gitignore
BUILD.bazel

With this change, it's much easier for bazel projects to depend on
Catch. They just need to add:
- In the workspace:
```
http_archive(
name = "com_github_catchorg_catch2",
urls = ["https://github.com/catchorg/Catch2/archive/v2.12.1.tar.gz"],
strip_prefix = "Catch2-2.12.1",
sha256 = "e5635c082282ea518a8dd7ee89796c8026af8ea9068cd7402fb1615deacd91c3",
)
```
Or the appropriate version/sha256.
- For the tests, assuming that `test_main.cc` contains the
`CATCH_CONFIG_MAIN`:
```
cc_library(
name = "test_main",
srcs = ["test_main.cc"],
deps = ["@com_github_catchorg_catch2//:catch2"],
)
```

Create a BUILD file for compatibility with bazel

---

.gitignore
BUILD.bazel

This PR adds support for easily depending on catch2 v3 as a Bazel dependency.
It adds 2 targets: `catch2` and `catch2_main`, with the `_main` version depending on the `catch2` library.
I didn't try to hide the `internal` headers (well, actually I tried and failed), but I guess that's the same as CMake (they're available by default).
To create a unit test, you just have to write a `BUILD` file like:
```bazel
cc_test(
name = "test",
srcs = ["test.cc"],
deps = ["@catch2//:catch2_main"],
copts = ["-std=c++14"],
)
```

Add Bazel support for the v3 branch

---

include/internal/catch_registry_hub.cpp
include/internal/catch_startup_exception_registry.cpp
include/internal/catch_startup_exception_registry.h
include/internal/catch_uncaught_exceptions.cpp

Some compilers, e.g. the Green Hills C++ compiler, react badly to the
appearance of std::exception_ptr, std::current_exception,
std::rethrow_exception and std::uncaught_exception(s). To allow usage of
Catch2 with these compilers when exceptions are disabled, hide the usage
of std::exception_ptr etc. when compiling with
CATCH_CONFIG_DISABLE_EXCEPTIONS.

Hide std::exception_ptr and friends if exceptions disabled

---

.clang-format

Initial `.clang-format` file, open for discussion. The config doesn't contain much as the defaults fit most cases already. Documentation of all options is available [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).
#1182

Clang-format configuration

---

docs/list-of-examples.md
examples/302-Gen-Table.cpp
examples/CMakeLists.txt

There are some examples on issue #850 of using this feature, but they are not easily found from the documentation. Adding them here as an example makes them more findable and ensures they keep working if the API changes.

Add an example of using GENERATE(table())

---

include/reporters/catch_reporter_xml.cpp
projects/SelfTest/Baselines/xml.sw.approved.txt

This adds a small additional output to the XML reporter: the number of passed/failed/expected-failed test *cases* and not just assertions. I am working with a team that is building somewhat of a system test, rather than unit test, with Catch2, and some assertions are called in a loop making the total assertion count not as helpful as the total test case count.
The approval tests appear to fail but for apparently unrelated reasons?

Add OverallResultsCases element to XML reporter

---

include/internal/catch_debugger.h

These changes resolve compilation issues for the Catch headers when compiling with macOS on ARM, which is not x86/x86_64 based. The changes are similar to the "elif defined(CATCH_PLATFORM_IPHONE)" logic later in these files.  ARM based macOS machines were already announced at Apple's WWDC.
The error being resolved looks like the following:
```
catch.hpp:8237:13: error: invalid token in expression
CATCH_BREAK_INTO_DEBUGGER();
^
catch.hpp:7948:83: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
#define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
^
catch.hpp:7913:34: note: expanded from macro 'CATCH_TRAP'
#define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
^
<inline asm>:1:6: note: instantiated into assembly here
int $3
^
```

Fix for macOS on ARM

---

docs/generators.md

If you want to write "2\*2" you need to escape the asterisk, or else it becomes formatting in Markdown.
None that I know of.

Escaping "*" ("times") to fix Markdown presentation

---

docs/command-line.md
include/internal/catch_commandline.cpp
include/internal/catch_config.cpp
include/internal/catch_config.hpp
include/internal/catch_interfaces_config.h
include/reporters/catch_reporter_bases.cpp
include/reporters/catch_reporter_bases.hpp
include/reporters/catch_reporter_compact.cpp
include/reporters/catch_reporter_console.cpp
projects/CMakeLists.txt
projects/SelfTest/TimingTests/Sleep.tests.cpp
projects/TestScripts/testTimeThreshold.py
single_include/catch2/catch.hpp

A test runner already has a --durations option to print durations.  However, this isn't entirely satisfactory.
When there are many tests, this produces output spam which makes it hard to find the test failure output.  Nevertheless, it is helpful to be informed of tests which are unusually slow.
Therefore, introduce a new option --min-duration that causes all durations above a certain threshold to be printed.  This allows slow tests to be visible without mentioning every test.
In our CI we're currently emulating this with [some ugly grep](https://github.com/CleverRaven/Cataclysm-DDA/blob/ef0197a5fb40f3937a0ad764ba097ff229cdbc4e/build-scripts/build.sh#L12) on the output, but this is a bit limited, and harder to use when running the tests outside of CI.
I've made a bunch of choices in this …

Add new command-line option to specify a threshold for test duration printing

---

src/catch2/internal/catch_clara.hpp

I upgraded to catch 3, including `<catch2/catch_session.hpp>` caused a warning under GCC 8 in clara,
this silences that warning
```
catch_clara_upstream.hpp:495:77: error: conversion to 'long unsigned int' from '__gnu_cxx::__normal_iterator<const std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >::difference_type' {aka 'long int'} may change the sign of the result [-Werror=sign-conversion]
auto count() const -> size_t { return m_tokenBuffer.size() + (itEnd - it); }
~~~~~~~^~~~~
```

Silence a -Wsign-conversio warning in Clara under GCC

---

contrib/ParseAndAddCatchTests.cmake

With CMake 3.18.0 the `add_test(NAME)` handling changed. The escaped
double quotes confuse the new call. Work around this upstream change.
Closes: https://github.com/catchorg/Catch2/issues/1984

Fix CMake add test helper for CMake 3.18.0

---

contrib/ParseAndAddCatchTests.cmake

https://cmake.org/cmake/help/v3.18/release/3.18.html#id1
In CMake 3.18.0 the add_test() command learned to support special characters in test names. This was accidentally left out of its release notes. Unfortunately the fix breaks existing projects that were using manual quoting or escaping to work around the prior limitation. This fix has been reverted in 3.18.1, but may be re-introduced in future versions of CMake with a policy for compatibility.

Update ParseAndAddCatchTests.cmake for cmake 3.18.1

---

CMakeLists.txt

When adding Catch2 as a subdirectory, a couple of choices in the main CMakeLists.txt file end up having a global effect:
* The `USE_FOLDERS` property is global; setting it affects the entire workspace.
* Including the `CTest` module will cause the generation of several new targets.
These global choices should be decided by the consuming project, not by one of its dependencies.  This change moves those settings into regions  guarded by `if(NOT_SUBPROJECT)`.  This should have no effect on Catch2 standalone builds, while being friendlier to consuming projects.
I'm not aware of any existing issues relevant to this PR.

Don't apply global settings when configuring as a subproject.

---

include/internal/catch_compiler_capabilities.h

This fixed buld errors for ubuntu-16 + clang and similar situations
where C++17 is supported in the compiler but not the default
C++ standard library.
Clang packages on ubuntu-16 use the clang compiler which supports C++17, but use the system-default C++ library which does not fully support C++17.  This results in compile errors where Catch2 mis-identifies support for std::bytes.
Closes #1992

Issue 1992: Better c++17 std::byte detection

---

include/internal/catch_tostring.h
projects/SelfTest/Baselines/compact.sw.approved.txt
projects/SelfTest/Baselines/console.std.approved.txt
projects/SelfTest/Baselines/console.sw.approved.txt
projects/SelfTest/Baselines/junit.sw.approved.txt
projects/SelfTest/Baselines/sonarqube.sw.approved.txt
projects/SelfTest/Baselines/xml.sw.approved.txt
projects/SelfTest/IntrospectiveTests/ToString.tests.cpp

Fix for issue #2003 
- Enhances `rangeToString` to work with a separate iterator and sentinel type
- Adds a test to ensure this compiles

Support sentinel-based ranges in default stringify

---

include/internal/catch_test_registry.h

The `0`s were needed for the expansion of parameter pack for the sake of
`expander`. Now when we have `index++` it is no more needed.

Remove superfluous values

---

src/catch2/internal/catch_console_colour.cpp

At some places, the colour reset code is printed after a newline. Since the default output buffering to console is line-based, the reset code is not actually written out. If messages from user code are printed to stderr (different stream, same console), they are printed before the colour reset code, and thus they are coloured.
Explicitly flushing the stream after writing the colour escape code solves this.

Fix unintended colouring of user's stderr on POSIX

---

include/internal/catch_compiler_capabilities.h

Disable `__builtin_constant_p` when compiling with nvcc, which could cause the compiler to crash as described in #2005.
Fixes #2005.

Disable __builtin_constant_p when compiling with nvcc

---

docs/cmake-integration.md

Since CMake 3.11 a new feature called FetchContent is available, that makes it easy to integrate external projects.
https://cmake.org/cmake/help/latest/module/FetchContent.html#fetch-content-examples

Docu/Show how to use CMake FetchContent

---

contrib/Catch.cmake
contrib/CatchAddTests.cmake
docs/cmake-integration.md

When using `catch_discover_tests` with `EXTRA_ARGS -o foo`, the test reports will be overwritten with each test case.
The args `REPORTER`, `OUTPUT_DIR`, `OUTPUT_PREFIX`, and `OUTPUT_SUFFIX` will allow for further customization of the test case runs.
* `REPORTER` can be any valid reporter of the Catch executable. 
The specified reporter will be validated against the available reporters of the Catch executable. 
* `OUTPUT_DIR` can be a relative or an absolute path.
If relative, it will be relative to the `WORKING_DIRECTORY`, which in turn defaults to `CMAKE_CURRENT_BINARY_DIR`.
* `OUTPUT_PREFIX` is a string that will be added before each test report name.
* `OUTPUT_SUFFIX` is a string that will be added after each test report name, e.g. a file extension.
Resolves  #1946

Add REPORTER and OUTPUT_DIR args to catch_discover_tests

---

contrib/ParseAndAddCatchTests.cmake

* Change regex to allow parentheses inside the test macro for a type list
* Append a wildcard to the CTestName if the test case is a template
* Also change the regular expression so parentheses are allowed in names
(fixes #1848)

Support template test cases in ParseAndAddCatchTests

---

contrib/CatchAddTests.cmake

In a CMake project, when using `catch_discover_tests(WORKING_DIRECTORY [...])` it usually means that the test binary needs resources that are relative to said working directory. This could lead to UB or a crash when running `--list-test-names-only` or `--list-reporters` on the produced test binary i.e when a .dll is not lazy loaded and not available in the current PATH.
This commit simply forwards the `WORKING_DIRECTORY` argument to the `execute_process()` calls.
This also remove the need of using CMake's own magic with `CMAKE_MSVCIDE_RUN_PATH` and the like...

Add WORKING_DIRECTORY to CatchAddTests.cmake commands

---

.gitignore
CMakeLists.txt
fuzzing/CMakeLists.txt
fuzzing/NullOStream.cpp
fuzzing/NullOStream.h
fuzzing/build_fuzzers.sh
fuzzing/fuzz_TestSpecParser.cpp
fuzzing/fuzz_XmlWriter.cpp
fuzzing/fuzz_textflow.cpp

This adds a fuzzer for the TestSpecParser and XmlWriter. I ran them for a few minutes, and it found nothing (unusual!).
This addition should not affect anyone, fuzzing is disabled by default.
I do not want to add more fuzzers, scripts, documentation etc at this point because I want to have early feedback. For instance, the cmake I wrote is probably horrible and there is some better way to do it.
Also, it is libFuzzer only. Making it oss-fuzz compatible can easily be done later (I have done that with simdjson and fmt).

add fuzzer for TestSpecParser and XmlWriter

---

extras/CatchAddTests.cmake

- don't warn on zero return code of `--list-reporters`
- previously return code was the number of reporters (#1410, #1146)
- as of 2c06ee9 return code is zero on success

fix warning in extras/CatchAddTests.cmake

---

docs/opensource-users.md

Add opensource users [laoshanxi/app-mesh] which is using Catch2 for Unit Test.
N/A

Add AppMesh to Open Source projects using Catch

---

src/catch2/internal/catch_compiler_capabilities.hpp

When using Clang on Windows the macro `CATCH_INTERNAL_START_WARNINGS_SUPPRESSION` gets redefined because both `__clang__` and `_MSC_VER` are set and both lead to a definition of this macro. This change is supposed to allow using Clang on Windows without such issue by adding additional condition to the clang's variant to prevent it taking effect when used with MSVC headers (clang-cl).
Resolves #2047

Prevent macro redefinition when using Clang with MSVC on Windows #2047

---

contrib/ParseAndAddCatchTests.cmake

CMake 3.19 introduces new add_test() behavior guarded with the policy
CMP0110.
See: https://cmake.org/cmake/help/latest/policy/CMP0110.html
Update the helper script ParseAndAddCatchTests to consider the policy and
handle the test case name accordingly.
Related issue (CMake 3.18.0): https://github.com/catchorg/Catch2/issues/1984

Consider CMP0110 add_test() policy

---

src/catch2/generators/catch_generators.hpp
tests/SelfTest/IntrospectiveTests/GeneratorsImpl.tests.cpp

Fix types in generators: decay types, properly constrain forwarding

---

contrib/ParseAndAddCatchTests.cmake
docs/opensource-users.md

Fix regex that requires two string arguments in the form of
TEST_CASE("a", "b") resulting in not finding TEST_CASE("a") entries.
See regex: https://regex101.com/r/rQe6Jd/1
Fixes: https://github.com/catchorg/Catch2/issues/2055

Fix CMake regex in ParseAndAddCatchTest helper
