catchorg/Catch2

.travis.yml
I read about https://github.com/philsquared/Catch/issues/511#issuecomment-145700281 via [your twitter](https://twitter.com/phil_nash/status/651284078138904576), and though instead of writing something, let actions speak. So here are some Travis CI improvements.
-----------------------------------------------------------------
In particular, this adds several improvements, such as:
- making use of container based infrastructure (faster startups, caching feature, 2 cpus, 4gb ram, ..)
- using ccache for faster building (we could also cache arbitrary directories)
- builds for linux and osx
- builds for various gcc, clang versions
- recent cmake installation
The Travis CI status for my fork looks like this, if you want to give it a try:
https://travis-ci.org/daniel-j-h/Catch
Related: what …
=> Improves the Travis CI integration

include/internal/catch_evaluate.hpp
=> Support explicit operator bool

.travis.yml
I'm not happy with this fix but I don't (currently) understand travis-ci well enough to fix the real problem.
For now this gets CI passing.
=> Quick fix for failing travis builds on OS X

include/reporters/catch_reporter_xml.hpp
=> Fix XmlReporter always writing first line to stdout

docs/test-cases-and-sections.md
I tried to make sure I wasn't changing any British spellings so I apologize if I've mixed any up.
=> Fixing a couple of typos

docs/own-main.md
For some reason, the GitHub online file editor also touched the last line...
=> own-main.md: fix typo

docs/opensource-users.md
=> Add ArangoDB

CMakeLists.txt
This "/" is not needed as CMake adds this automatically
=> remove redundant "/"

docs/opensource-users.md
Add https://github.com/lexicalunit/nanodbc/
=> Add nanodbc library to Catch users

docs/opensource-users.md
I'm the maintainer of the Newsbeuter project and I'm using Catch to get confidence to refactor decade-old code. Will be happy to be on your users list. Thank you for the great library!
=> Add Newsbeuter to OSS users list

docs/tutorial.md
=> fixed spelling error in tutorial.md

docs/opensource-users.md
=> Added 'args' argument parser library to users

contrib/ParseAndAddCatchTests.cmake
Just adding more flexibility for the cmake catch parsing script. No functional changes, mostly control over existing ones. For example, currently it always adds all tests with [!hide] tag which is not what I want. Meanwhile, I still want those tests to be compilable for a reason. Same for naming the tests -- for me, it's overkill to add fixtures and project name to the test name. For others it may be fine. I feel like configuration here is nice to have.
=> Adding more flexibility into the cmake catch parsing script

docs/matchers.md
Update matchers documentation as per #972. Added a line in the first example making it clear that the built-in matchers are not in the global namespace.
Closes #972
=> Update matchers docs to reflect namespace usage

docs/opensource-users.md
Add [Giada](https://github.com/monocasual/giada) to the open-source users list.
=> Add open-source user

conanfile.py
See header-only guidelines: 
http://conanio.readthedocs.io/en/latest/howtos/header_only.html?highlight=header%20only
Its borderline cosmetic, but it does have a purpose.
=> Minor - added header-only flag in conan

README.md
This PR updates the Readme link to the single header include file to latest release (catch2 dev.4).
=> Direct link to the single header file updated to latest release (dev.4).

docs/opensource-users.md
=> Fix very minor typo

docs/assertions.md
scale more detailed explained (and incomplete sentence removed); have to be adapted to PR #1068 (formula and default value) if necessary
=> extension of scale explanation

docs/assertions.md
=> Trivial typo fix.

docs/opensource-users.md
Just a small documentation update
=> Add fuxedo.io to open source users

CMakeLists.txt, include/internal/catch_config.cpp, include/internal/catch_config.hpp, include/internal/catch_interfaces_config.h, include/internal/catch_list.cpp, include/internal/catch_session.cpp, projects/SelfTest/Baselines/compact.sw.approved.txt, projects/SelfTest/Baselines/console.std.approved.txt, projects/SelfTest/Baselines/console.sw.approved.txt, projects/SelfTest/Baselines/console.swa4.approved.txt, projects/SelfTest/Baselines/junit.sw.approved.txt, projects/SelfTest/Baselines/xml.sw.approved.txt, projects/SelfTest/IntrospectiveTests/CmdLine.tests.cpp, projects/SelfTest/UsageTests/Misc.tests.cpp
resolves https://github.com/catchorg/Catch2/issues/1175
=> don't list hidden tests by default

docs/opensource-users.md
Adds [SpECTRE](https://github.com/sxs-collaboration/spectre) project to the list of open source projects.
=> Add SpECTRE project to list of users.

docs/opensource-users.md
Suggestion for adding libcluon as we are also using Catch2 for testing.
=> Suggestion for adding libcluon that is also using Catch2 for testing

include/internal/catch_output_redirect.cpp
See #1270 and commit [ae590fe](https://github.com/catchorg/Catch2/commit/ae590fe2163270685ebec4ed1541d3e8e9401692).
Commit didn't fix error and just cause new errors.
See #1257 and commit [c651f23](https://github.com/catchorg/Catch2/commit/c651f239f01dde9e132b1a3d06fd9b1b6246b189).
Commit didn't fix error and just cause new error.
Closes #1270 finally.
Closes #1257 finally.
=> Fix compilation

docs/list-of-examples.md
Link number 2 was directed to number 1.
Link number 2 was mistakenly directed to link number 1.  I edited the link to be correctly directed to number 2.
=> This fixes Multiple-file example link #2.

include/internal/catch_leak_detector.cpp
Replace TABs with four (4) spaces in source files.
=> Code: TABs to Spaces

docs/list-of-examples.md, docs/reporters.md, examples/200-Rpt-CatchMain.cpp, examples/207-Rpt-TeamCityReporter.cpp, examples/CMakeLists.txt
See issue #1037 
As a long time past between creating part 1 and this little piece, I'm not sure if it's acceptable to work in smaller badges than with part 1 and just review / merge it, or to expand it first.
=> [Documentation] Examples part 2

docs/why-catch.md
=> Fix Cute test framework URL

docs/opensource-users.md
Add an entry in the list of opensource user for [cppcodec](https://github.com/tplgy/cppcodec)
=> Add cppcodec in opensource users

include/internal/catch_interfaces_testcase.h, include/internal/catch_stringref.h
=> small cleanup of code

docs/commercial-users.md
Our favorite unit test framework. Thanks!
=> Added Bloomlife to list of commercial users

include/internal/catch_console_colour.cpp
=> Console Colour: fix compilation

include/reporters/catch_reporter_junit.cpp, projects/SelfTest/Baselines/junit.sw.approved.txt
=> junit reporter reports random seed (--rng-seed)

README.md
=> Update url of blog post

docs/assertions.md, docs/opensource-users.md, docs/tutorial.md
Minor changes to to the documentation, to update a URL that was redirecting, and other small things like:
* expanding an abbreviation that not all readers will know
* remove commas so that reading a sentence flows
* adding the odd missing word
None
=> Documentation improvements

docs/tostring.md
New documentation needed "and".
=> Add missing word

CMakeLists.txt, conanfile.py
=> Prevent building in source dir

docs/command-line.md
=> Adding to documentation for --order and --rng-seed

docs/opensource-users.md
=> Add PopHead to list of Open Source projects using Catch

docs/commercial-users.md
=> add UX3D to commercial users

docs/generators.md, include/internal/catch_generators.hpp
update name of Value Generators in doc to match class names
=> update name of Value Generators in doc to match class names

docs/opensource-users.md
=> Remove JSON library from users

conanfile.py
Conan topic cleaned up as suggested in #1832.
#1832
=> Conan topic cleanup.

examples/210-Evt-EventListeners.cpp, examples/231-Cfg-OutputStreams.cpp, include/internal/catch_commandline.cpp, include/internal/catch_console_colour.cpp, include/internal/catch_enum_values_registry.cpp, include/internal/catch_message.cpp, include/internal/catch_session.cpp, include/internal/catch_test_case_info.cpp, include/internal/catch_test_case_tracker.cpp, include/reporters/catch_reporter_junit.cpp, projects/SelfTest/UsageTests/ToStringVector.tests.cpp
A few minor refactorings and modernizations. The full list is included in the commit message.
_-none-_
=> A few minor refactorings

.conan/build.py, .conan/test_package/CMakeLists.txt, .conan/test_package/conanfile.py, conanfile.py
I didn't read the contributor documentation btw
=> Resolve minor issues with Conan integration

docs/commercial-users.md
Self-explanatory documentation change
=> Fix typo in link in docs

docs/Readme.md
self-explanatory documentation change.
=> Add link to list of commercial user projects

include/internal/catch_list.cpp, projects/SelfTest/UsageTests/Tricky.tests.cpp
- stdioh. replaced with cstdio
- Local variables made const
*- none -*
=> Refactoring

docs/commercial-users.md
Several teams here at (game development company) King make use of this excellent testing library and we would want to be included in the list of commercial users.
N/A
=> Add king as commercial user

docs/slow-compiles.md
=> fix: typo; Update slow-compiles.md

include/internal/catch_debugger.cpp
I switched out the deprecated C headers for the STL, and replaced them for the C++ ones.
=> Replace Deprecated C-Headers with the C++ ones

docs/contributing.md
This took me some time to figure out, so document for others.
Adding a section to the contributor guide seems like the correct place to me.
=> Add notes on compiling the examples.

docs/contributing.md
Updates contributing docs to account for clang-format, explain how to compile examples and so on.
=> Update contributing docs

src/catch2/internal/catch_clara_upstream.hpp
=> Remove extra semi-colons

docs/generators.md
=> Fix typo in generators docs

docs/generators.md
j was not declared in `SECTION("two")`
=> fixes bug in example - undeclared identifier

docs/generators.md
=> Add missing syntax highlighting tag
